### ISSUE TITLE
ES Module-style component exports?

### ISSUE THREAD

**Issue by jadennnn** [hybridsjs/hybrids#102]
Hi!

I like the direction this library is taking with web components and would like to use it. I've been playing around with it (evaluating it) and I ran up against something that I didn't find an answer to in the docs.

How do I import/export components from module files and use them?

I saw the example of exporting it:
```js
export const SimpleCounter = {
  count: 0,
  render: ({ count }) => html`
    <button onclick="${increaseCount}">
      Count: ${count}
    </button>
  `,
};
```

But, how do I import it and use it well? I'd like to do something like:
```js
import { SimpleCounter } from './simpleCounter.js';

export const SimpleContainer = {
  render: () => html`
    ${ SimpleCounter() }
  `
};
```
Instead of using the elements via their html tag (e.g. `<simple-counter></simple-counter>`).

This is useful because of the programmatic usage - `${ SimpleCounter() }` can be checked & linted via webpack/ESLint/Typescript. With HTML tags like `<simple-counter>` I can't have those checks.

Thanks!

**Comment by jadennnn** [comment]
Well, I'm working my way through this and found something.

The result of the `define()` call returns the class for your custom element. You can call `new <your class object>()` and you get a DOM element. But I'm not sure yet how to use this in the HTML templates since you can't just:
```js
html`
<div>${ new MyCustomElementClass() }</div>
`
```

**Comment by smalluban** [comment]
Hi @jadennnn!

The library does not support passing the definition directly into the template. The template text content gives more flexibility. In your last example, there would be a problem with setting dynamic attributes or even pass static ones. The structure of the template is a text, which is compiled to live DOM. This is much closer to the specifications, as it works like you would pass an HTML file to the browser. What you would like to have is something similar to the virtual dom concept, where everything is a JavaScript code (like JSX syntax).

However, you don't have to define elements before you want to use them. The template engine has `.define()` helper, which allows defining elements dynamically, only if they are needed. The engine also checks in development mode if all used custom elements in the template are already defined, which protects from hard to detect errors.

For example, you can write the template like this (where import is a hybrids component definition or custom element constructor):

```javascript
import MyCustomElement from './MyCustomElement';

html`
  <div>
    <my-custom-element></my-custom-element>
  </div>
`.define({ MyCustomElement })
```

**Comment by jadennnn** [comment]
Thank you!
Hm, that might actually be fine then, especially since the custom elements are checked in development mode.
You're right - the JSX/everything-in-JS popularity has spoiled me in regards to static analysis. But I'd guess there's a way to hook up the development version to "lint" your project for invalid custom element tags in a build system.
