### ISSUE TITLE
Render function not getting called in weird edge case

### ISSUE THREAD

**Issue by rubixibuc** [hybridsjs/hybrids#105]
As strange as this case seems, I actually ran into it during development.

This [https://stackblitz.com/edit/hybrids-children-factory-csbtmg](https://stackblitz.com/edit/hybrids-children-factory-csbtmg) has documentation and use cases within. but basically:

When I'm updating a prop that depends on another one, render get's called correctly each time, but this doesn't work when there's a third prop changed in between.

Again sorry for all of the issues, really appreciate any help!

**Comment by smalluban** [comment]
Yep, there was a bug. I discovered that too a few days ago during tests of the new store feature. I had to add it when I slightly refactored the cache mechanism to be more flatten and much faster. The cache deps are cleared when the property must be recalculated, but its dependencies may not need that action, so then deeper deps are not passed to the root. 

Fortunately, it is already fixed, so you can update the library to `v4.1.7` ;) The details of the fix you can find here: https://github.com/hybridsjs/hybrids/commit/ee85006725dab9c092ed262506bb739094553c77
