### ISSUE TITLE
why stackblits?

### ISSUE THREAD

**Issue by kostadinnm** [hybridsjs/hybrids#106]
Hello.

The question is why an online platform is chosen for the demos?! There are so many developers each having their own editor, environtment, etc. When downloading an archive from stackblits I cannot run it locally even when installing the packages - it seems it uses some convention around index.html/index.js. Imho, that is quite ambiguous. My personal preference for 'installable' editor is mostly motivated by the fact that I have best font rendering(of the source code), while in-browser ones are not quite good(for which I can present evidence, but that's not the point). Maybe you thought that would enable hybrids rendering correctly, including the polifils, but if the authors would like more devs trying it out, it should be more accessible to play with. Moreover, users that try new webcomponents' tech rarely would have old browsers or be naive not having poliflls' strategy for their products. Please don't be extravagant - let this lovely new lib get traction, because it has real potential.

Cheers,
Kostadin

**Comment by smalluban** [comment]
Hi @kostadinnm! I wish I had more time ;) (I have some, but I am still super focused on finishing #85). I want to move all docs examples to codesandbox.io. I didn't do it in the first place because I wanted to have IDE, which supports all of the browsers. Two years ago it even didn't work well for Firefox, which in that time required polyfills. 

The current situation is much different. Also, I think that support for older browsers is only for those who really need it, so docs examples might be shown in the modern environment. You can expect, that soon all of the examples will be available on the new platform. The first step is done - I've connected it to the PRs, so you can test a new version of the library in the codesandbox.io even before it is released (its bot comments with a link to the template).

**Comment by kostadinnm** [comment]
Ok, I'd been just picky, but if you feel you may close this. Oh, I'm just noticing you've marked it as a feature, so it is up to you if you need to track something over this.

**Comment by smalluban** [comment]
I will leave this issue open to remind me, that it should be done soon ;) I'll also let you know when I update links to demos.

**Comment by kostadinnm** [comment]
btw, I'm revisiting the docs and went trough `descriptors` and `factories` yesterday. All in all, I am able to grasp the ideas, but the examples are somewhat incapable to demonstrate all the capabilities. I've sketched one over descriptors(around an 'address' prop), but that for a `factory` seems to me even kind of deceiving. I think I've enhanced it so that it's much more clear what a factory is doing(for which I may be wrong). Here is the code:
```
import { html, define } from 'hybrids';
// import titleFactory from './titleFactory';

function titleFactory(defaultValue, defaultTitle = '') {
  return {
    // this is not needed, as setting doc title is a side effect and may go into observe
    // set: (host, value) => { document.title = value; return value; },
    connect: (host, key) => {
      if (host[key] === undefined) {
        document.title += defaultTitle; // toConsider: add " - " separator
      }
      host[key] = defaultValue;
    },
    observe: (host, value, lastValue) => {
      const docTitle = document.title;
      if (lastValue) {
        const lastValueIndex = docTitle.lastIndexOf(`${lastValue}`);
        if (lastValueIndex > 0)
        {
          // toConsider: add " - " separator
          document.title = docTitle.slice(0, lastValueIndex) + docTitle.slice(lastValueIndex, `${value}`)
        }
      }
    }
  }
}


export function increaseCount(host) {
  host.count += 1;
}

export const TitleCounter = {
  count: titleFactory(0, '0'), // definition changed from "count: 0"
  render: ({ count }) => html`
    <button onclick="${increaseCount}">
      Count: ${count}
    </button>
  `,
};

define('title-counter', TitleCounter);

```

Tell me if you find this better?!
Kind regards,
Kostadin

**Comment by smalluban** [comment]
It looks much better than in docs! When I was writing this section the `observe()` wasn't available yet. I think it is a good idea to update the example. In the original version, there are more things missing. For example, the property is no longer bound to the attribute value (it does not use `property()` factory). I know that you wanted to make it more useful with logic inside of the `observe`, but I think it might distract the purpose of the example.

I would recommend something like this: 

```javascript
import { property } from "hybrids";

function titleFactory(defaultValue, defaultTitle = '') {
  return {
    ...property(defaultValue, (host, key) => {
      if (host[key] === undefined) {
        document.title = defaultTitle;
      }
    }),
    observe(host, value) {
      document.title = value;
    },
}
```

The property factories generate `descriptor` object, so we can use the spread operator to use all of the `property()` features, and add own `observe()` method. The example is rather simplified but shows the concept. What do you think?

**Comment by kostadinnm** [comment]
Well, I am following the docs sequentially and the `property` factory is not presented there yet. Other than that, when writing the example myself, I'd been feeling it may get decoupled from the value as well, just I couldn't have realized how it could be done with hybrids' bits and pieces. The `factories` section is short anyway, so if you decide, both may be included.

As a side thing, I noticed you mention dealing with some `store` stuff. While I am trying to move on with a prototype, which has a #cqrs #eventsourcing backend library [wolkenkit](https://www.wolkenkit.io/) ([github page](https://github.com/thenativeweb/wolkenkit)), I am eager to learn any insights of what frontend app-state store mechanizms will be pluggable to/with `hybrids` and whether those will be compatible with their so called [wolkenkit client](https://www.npmjs.com/package/wolkenkit-client) ([github link](https://github.com/thenativeweb/wolkenkit-client-js)). I've grasped they're leaning on demoing through `react`(along with `nextjs` for some ssr stuff), but I have some feeling pure `hybrids` backed by pure `wolkenkit` will be a killer combo.

Cheers,
Kostadin

**Comment by smalluban** [comment]
Thanks for the comment. Whatsoever, I will update the docs for the `titleFactory`. 

I will look at the wolkenkit, and let you know. The `store` feature is still in progress, but you can look at the #85, especially tests, which show how it works. It almost ready, I have started testing it out for real-world scenarios, and I plan to add a `store` factory on top of the methods available now - `store.get()`, `store.set()`, etc... 

In short, the idea is to provide a full declarative approach to define your data model and combine it with the connection to the external source. In the current state of the art, usually, data state management libraries are agnostic about the source of data, and require control loading states, etc, by yourself. The `store` makes no difference between sync or async data source and hide the fetching data behind the scene. You only care about what you want, not how you get it. With `store` you will do something like this:

```javascript
import { store } from "hybrids";
const User = {
  firstName: '',
  lastName: '',
  [store.connect]: myApi("/users"),
};

const UserList = {
  users: store([User]),
  render: ({ users }) => html`
     <ul>
       ${store.pending(users) && html`Loading...`}
       ${store.ready(users) && users.map(user => html`
         <li>${user.firstName} ${user.lastName}</li>
        `)}
      </ul>
  `,
};
```

The above example is just a simple example. There is much more, like relations between models, full time-based cache, etc.

**Comment by kostadinnm** [comment]
That'd be very nice. In the same direction, consider building a low-level property `descriptor` for asynchronous picking of a geo address, which calls out to an online api for the full details. Here's some code:
```
// simplistic store:
const addressCache = {};
function buildAddressFromFakeGoogle(address, callback) {
    if (addressCache[address]) {
        callback();
    } else {
        fakeGoogleApi.getFullAddress(address).then(fullAddress => {
            addressCache[address] = fullAddress;
            callback();
        })
    }
    // toConsider: clear cache per component(i.e. utilize host + key)
    return () => { addressCache[address] = undefined; } // clears only the initial value
}

function isValidAddressChange(prevAddress, nextAddress) {
    if (prevAddress === nextAddress) { return false; } //cannot be equal
    if (prevAddress.country !== nextAddress.country) { return false; } // cannot change country
    return true;
}

const asyncAddressDescriptor = {
    connect: (host, key, invalidate) => {
        host[key] = "Greenwich";
        const onAddressCacheDispose = buildAddressFromFakeGoogle(host[key], invalidate);
        return () => {
            onAddressCacheDispose();
        }
    },
    set: (host, value, lastValue) => {
        if (isValidAddressChange(lastValue, value)) {
            if (addressCache[value]) {
                return value;
            } else {
                buildAddressFromFakeGoogle(value, () => {
                    // cannot invoke set from here to invalidate the prop value cache:
                    // host[key] = value; | invalidate();
                });
                return lastValue;
            }
        }
        throw new Exception(`Address change ${lastValue} -> ${value} not valid`);
    },
    get: (host, lastValue) => {
        return addressCache[lastValue];
    }
}
```

My question is, why is the setter(as you call it `assertive cache invalidation`) immediate only and there is no mechanism of deferring its execution like within `connect`'s `invalidate`-callback?! If you had to pick one of `key`/`invalidate` to include in the setter, will it break some of the concepts you're following or I am missing something and that example is not quite relevant!? As I am writing this, I kind of lean to trusting you in leaving the setter clean of async logic(just a simple reaction to user input, right). But still, that `invalidate` logic in `connect` is being felt to me as a `descriptors`' capability without continuation somehow. Had there be more examples, it wouldn't have felt that way I guess..

Cheers,
Kostadin

**Comment by kostadinnm** [comment]
Hm, I've refined my meta-example to extend on the `store`, because it was too oversimplified and not rely on `invalidate` or `key` in the setter:
```
// simplistic store:
const addressStore = {
    cache: {},
    subscriberCallbacks: {},
    subscribe: (component, callback) => {
        subscriberCallbacks[component] = callback;
        return () => { subscriberCallbacks[component] = undefined };
    },
    fetchAddress(address, component = undefined) {
        if (cache[address]) {
            component && subscriberCallbacks[component]();
        } else {
            fakeGoogleApi.getFullAddress(address).then(fullAddress => {
                cache[address] = fullAddress;
                component && subscriberCallbacks[component]();
            });
        }
    }
}

function isValidAddressChange(prevAddress, nextAddress) {
    if (prevAddress === nextAddress) { return false; } //cannot be equal
    if (prevAddress.country !== nextAddress.country) { return false; } // cannot change country
    return true;
}

const asyncAddressDescriptor = {
    connect: (host, key, invalidate) => {
        const onAddressCacheDispose = addressStore.subscribe(host, invalidate);
        host[key] = "Greenwich";
        addressStore.fetchAddress("Greenwich", host);
        return () => {
            onAddressCacheDispose();
        }
    },
    set: (host, value, lastValue) => {
        if (isValidAddressChange(lastValue, value)) {
            addressStore.fetchAddress(value, host)
            return lastValue;
        }
        throw new Exception(`Address change ${lastValue} -> ${value} not valid`);
    },
    get: (host, lastValue) => {
        return addressStore.cache[lastValue];
    }
}
```

Had there be an `observer`, it would get called synchronously/asynchronously whenever the `store` have a cache hit or calls the referenced invalidation callback. As a detail to point out, I may need to verify the uniqueness of the `host` as a key - maybe some hash algorithm over it, but I have to try it out.

**Comment by smalluban** [comment]
@kostadinnm Please create a separate issue for the above problem. The main subject of this issue is different. It will be easier for other people to find a helpful solutions in the future.

**Comment by kostadinnm** [comment]
Well, after the refinement, it becomes less of an issue, but I may open a new one anyways. I see it as a clarification over the `store`-notion capabilities of hybrids, rather than a concrete question/issue though.

**Comment by smalluban** [comment]
Doc examples moved to the CodeSanbox ;) Thanks for the issue, it definitely helped me to push things forward :)

**Comment by smalluban** [comment]
@kostadinnm The store feature is live, so you might want to look at the [docs](https://hybrids.js.org/store/introduction) and try it ;)

**Comment by kostadinnm** [comment]
> @kostadinnm The store feature is live, so you might want to look at the [docs](https://hybrids.js.org/store/introduction) and try it ;)

Wow, it's so refreshing to see it - I've just passed through the docs in one breath and it seems spot on! I'll try utilize it, but hadn't had much time to play with my side-project. It's seems that it fills all the requirements of a client store.

**Comment by kostadinnm** [comment]
@smalluban , have you heard of the new html thing - portals. Here's an opinionated(imo) over-the-surface glance at that new stuff: https://www.youtube.com/watch?v=e1L2WgXu2JY

**Comment by smalluban** [comment]
I have seen portals once in the Google I/O videos a year ago or so. It has some potential, but I think the usage in the wild will be limited. As it requires additional registration of the domain, and it is specially built for cross-domain navigation.

**Comment by kostadinnm** [comment]
Hey, @smalluban why not open the new github feature - discussions.
https://i.imgur.com/EIDoShd.png
We may utilize it to add some useful stuff there. You may use it as a faq-section until you shape one within the official site?
Kind regards,
Kostadin

**Comment by smalluban** [comment]
Nice idea. I did not find it useful before, as I thought that users will use it instead of issues, which can make things messy. However, we can give it a try :)

**Comment by smalluban** [comment]
Here you have it: https://github.com/hybridsjs/hybrids/discussions
