### ISSUE TITLE
Firebase: Event subscriptions based off of other properties

### ISSUE THREAD

**Issue by rubixibuc** [hybridsjs/hybrids#108]
Hello again!

I have a use case where I need to subscribe to an api, but one of the component properties is used to subscribe. This is what I have so far: 

```javascript
const value = (path) => ({
  connect: (host, key) => {
    const handler = (snapshot) => {
      host[key] = snapshot.val();
    };

    database.ref(path(host)).on("value", handler);
    return () => {
      database.ref(path(host)).off("value", handler);
    };
  },
});
```

```javascript
const WrapperComponent = {
  id: "",
  listOfIds: value((host) => `entity1/${host.id}/children`),
  render: (host) => html`
    ${host.listOfIds
      ? host.listOfIds.map((id) =>
          html`<inner-component=${id}></inner-component>`.key(id)
        )
      : html`List Empty`}
  `,
};
```

```javascript
const InnerComponent = {
  id: "",
  data1: value((host) => `entity2/${host.id}/data1`),
  data2: value((host) => `entity2/${host.id}/data2`),
  render: (host) => html`
      <div>${host.data1}</div>
      <div>${host.data2}</div>
  `,
};
```

**The problem is in the inner component `host.id` is not defined before the connect handler is invoked, even though I provide it when the component is declared in the html.** When I use the component directly inside a html page it works, but not inside of another hybrid

Is there a better way to handle this type of subscription?

Ty!

**Comment by smalluban** [comment]
Hi @rubixibuc! Thanks in advance for the interesting use case. 

By the way, I don't recommend overwriting built-in `id` property (hybrids elements are still normal elements with HTMLElement prototype). Of course, it is not a cause of the problem, but its native functionality is gone (it is not attached to the prototype anymore). 

If there would be a solution keeping your concept, your both elements won't change data source after attaching to the DOM. When property relays on other properties, it is not a good idea to set up it only in connect method. The `id` property might change. 

In your case, there are two difficult factors. The first obstacle is with firebase returning data in the callback, which should be set to your property value. It would be much easier if the callback would notify about change, but we could use some other function to get current value (this is how the redux store works - we are notified by the subscribe method, but then we use `getState()` to receive the current state of the store). The second is a dynamic path, which has to be used when the callback is attached. As a result, if we want to pack it in a single property, defined by the factory, the value of the property must be an object holding not only a current value, but also current configuration. 

The below code shows how to do it. Its API allows setting property with mapping function to the path. It can be set by assertion, like `el.data1 = "12"`, which changes config value. In the `observe()` callback, it updates the event listener to the current path. Callback for setting value is set up in the connect method (this the only place, where you know the `key`).

I didn't test it (or even run it), so please let me know if it works (or has any bugs there). I would like to update it, for future readers.

```javascript
function firebase(database, mapPath = (v) => v) {
  return {
    set: (host, value, lastValue = {}) => {
      // If we set path, like el.data1 = "21";
      if (typeof value === "string") {
        const path = value.path && mapPath(value.path);
        // if path didn't change, keep the last value
        if (path === lastValue.path) {
          return lastValue;
        } else {
          value = { path: value };
        }
      }
      
      return {
        ...lastValue,
        ...value,
      };
    },
    // update callback if path changes
    observe: (host, value, lastValue) => {
      if (lastValue && lastValue.path) {
        database.ref(lastValue.path).off("value", lastValue.callback);
      }
      database.ref(value.path).on("value", value.callback);
    },
    
    connect: (host, key) => {
      // initialize callback for updating changes
      host[key] = { callback: (snapshot) => { host[key] = { value: snapshot.val() } };

      // clear callback on disconnect lifecycle
      return () => {
        const lastValue = host[key];
        if (lastValue.path) {
          database.ref(lastValue.path).off("value", lastValue.callback);
        }
      };
    },
  }
}

const InnerComponent = {
  data1: firebase(database, (id) => `entity2/${id}/data1`),
  render: ({ data1 }) => html`
    ${data1.value && html`This is data: ${data1.value}`}
  `,
};

const WrapperComponent = {
  listOfIds: firebase(database, (id) => `entity1/${id}/children`)
  render: ({ listOfIds }) => html`
    ${listOfIds.value 
      && listOfIds.value.map(id => html`<inner-component data1="${id}"></inner-component>`)
    }
  `.define({ InnerComponent }),
};
```

**Comment by rubixibuc** [comment]
I don't think it works because connect is called before it initializes that property from the attribute. So it never sets the path

**Comment by smalluban** [comment]
Finally, I tried to run it, so there were some syntax bugs. However, I end up with another solution. I think callback must be treated as a side effect. I tried to compile everything into one property, but it is overcomplicated. 

Here you have factory, which creates a connection to the database by one property (there you control the path) and uses `target` argument to update the second prop with data:

```javascript
import { property } from 'hybrids';

function firebase(database, target, mapPath = v => v) {
  const hostMap = new WeakMap();

  return {
    ...property(mapPath, (host, key) => {
      hostMap.set(host, (snapshot) => {
        host[target] = snapshot.val();
      });

      return () => {
        const lastValue = host[key];
        if (lastValue) {
          database.ref(lastValue).off("value", hostMap.get(host));
        }
      }
    }),
    observe: (host, value, lastValue) => {
      if (lastValue) {
        database.ref(lastValue).off("value", hostMap.get(host));
      }

      if (value) database.ref(value).on("value", hostMap.get(host));
    },
  };
}
```

It is better for yet another reason - you can use properties with own validation (`property()` transform types of values), so you can use it like this:

```javascript
const MyComponent = {
  connect: firebase(database, 'data'),
  data: 0,
  render: ({ data }) => html`
    Data from the database: ${data}
  `,
};
```

Then you can use your component with attributes or dynamic properties:

```javascript
html`
  <my-component connect="path/to/my/data"></my-component>
  <my-component connect="${dynamicId}"></my-component>
`
```

**Comment by rubixibuc** [comment]
I just came up with this.. after a lot of thinking about it

```javascript
const onValue = (ref, cb) => {
  database.ref(ref).on("value", cb);
};

const offValue (ref, cb) => {
  database.ref(ref).off("value", cb);
};

const snapshotValue = (cb) => (snapshot) => cb(snapshot.val());

const firebase = (refs) => {
  return {
    get: (host) =>
      Object.entries(refs(host)).reduce(
        (refs, [key, ref]) => ({
          ...refs,
          [ref]: snapshotValue((value) => {
            host[key] = value;
          }),
        }),
        {}
      ),
    observe: (host, value, lastValue) => {
      if (lastValue) {
        Object.entries(value).forEach(([ref, cb]) => offValue(ref, cb));
      }

      if (value) {
        Object.entries(value).forEach(([ref, cb]) => onValue(ref, cb));
      }
    },
  };
};
```

this allows for something like this, kinda like redux

```javascript
const Component = {
    key: '',
    connect: firebase(((host) => ({ data1: getDataRef1(host.key), data2: getDataRef2(host.key) 
    data1: '',
    data2: 0
}
```

**Comment by smalluban** [comment]
When `refs()` changes, the value of `cb` changes as well, but firebase requires to call `off` with the callback, which was attached. In your code in that situation, it is gone. 

I think there is one more possible solution:

```javascript
import { property } from 'hybrids';

function firebase(database, mapRef) {
  const callbacks = new WeakMap();
  const refs = new WeakMap();

  return {
    get(host, lastValue) {
      const cb = callbacks.get(host);
      const lastRef = refs.get(host);
      const nextRef = mapRef(host);

      if (nextRef !== lastRef) {
         refs.set(host, nextRef);

         if (lastRef) database.ref(lastRef).off("value", cb);
         database.ref(nextRef).on("value", cb)
      }

      return lastValue;
    },
    set: (host, value) => value,
    connect(host, key, invalidate) {
      callbacks.set(host, (snapshot) => { host[key] = snapshot.val(); });
      invalidate();
      return () => {
        const ref = refs.get(host);
        if (ref) database.ref(ref).off("value", callbacks.get(host));
      };
    },
  };
}
```

The getter depends on `mapRef`, so it will invalidate whenever the ref to data changes. It also only attaches to the database if data is actually used. We use simple setter, which replaces data (it is used in the callback).

With that way you can use it as simple as that:

```javascript
const MyComponent = {
  key: '',
  data1: firebase(database, ({ key }) => `/path/to/data/${key}`),
  data2: firebase(database, ({ key }) => `/path/to/other/data/${key}`),
};
```

**Comment by rubixibuc** [comment]
Major improvement over what I wrote :)

This satisfies all of my requirements!

**Comment by rubixibuc** [comment]
This worked great, ty!

**Comment by smalluban** [comment]
Cool 😎
