### ISSUE TITLE
Use Constructable Stylesheets for performance boost on many elements

### ISSUE THREAD

**Issue by dobexx** [hybridsjs/hybrids#112]
Hello,

so far I use Lit-Element / Lit-HTML. There is the integration of Constructable Stylesheets for some time now, which brings an enormous performance increase when using many Web Components. 

- https://developers.google.com/web/updates/2019/02/constructable-stylesheets
- https://github.com/Polymer/lit-html/issues/689

According to my assessment, this could be integrated without any problems, e.g. a factory function.

Is something like this planned in the near future?

Best regards
Marcel

**Comment by smalluban** [comment]
Yes, I've been planing adding this feature as far as it was published. However, I am not sure if they finally stabilize the API, so it will be implemented somewhere else than Chromium. Do you know anything about it?

The best place for the implementation is the `html.styles` helper method. It takes string values of the CSS. For now, it creates `<style>` tags inside of the template, but where the Constructable Stylesheets are supported it could create one and apply it to the instances of the template. It could possibly be used across multiple elements (the template instance has access to the host element).

**Comment by dobexx** [comment]
Thank you @smalluban very much for the first assessment and the super fast answer.

Since this was firmly integrated into Lit-Element as a stable and is accordingly encapsulated by the concrete implementation via the css literal, I am not concerned about possible changes. 

If you use html.styles for integration, this could be a great template for your own:

- https://github.com/Polymer/lit-element/blob/master/src/lib/css-tag.ts
- https://github.com/Polymer/lit-element/blob/c361d57450f00a8557227e7c4fe8c46b44010b20/src/lit-element.ts#L260

**Comment by smalluban** [comment]
Cool, so lets this issue be open, and I will try to look at this. Unfortunately, my time is a little bit limited right now, so I would assume that it can hit the master branch at about end of May or later.

**Comment by dobexx** [comment]
That sounds excellent. 

We will be focusing more closely on the large-scale migration of our polymer and lit-element infrastructure, which has been started in the past, towards hybrids, because we simply like the approach much better.

**Comment by smalluban** [comment]
Sounds great! It really makes me want to do it right now :) I'll try to push it forward as soon as possible.
