### ISSUE TITLE
Transferred properties of polymer change behaviour of hybrid components 

### ISSUE THREAD

**Issue by dobexx** [hybridsjs/hybrids#114]
Currently we are planning to migrate many of our previous hundreds of polymer elements to Lit element and now hybrids.

We have noticed that the transfer of properties leads to strange behavior in hybrid components.

This test setting illustrates this quite well:

https://stackblitz.com/edit/hybrids-simple-counter-evd6xi?file=polymer-el.js

If I click on "Set 66 to Polymer property for passing", the value is not passed on to the simple-counter.

Strangely enough, sometimes even the simple-counter can't even be set directly from the console via "$0.count = 33". Also clicking on "Count: xx" inside the hybrid element does not change the "count" property.

**Comment by smalluban** [comment]
There is a simple solution. Switch order of the definition of the components and it works then:

```javascript
import './simple-counter';
import './polymer-el';
```

The problem is on the Polymer template implementation. The template is compiled, when the element is defined, so in that time the `<simple-counter>` is not yet real custom elements. It does not have `count` property in the prototype, so the binding in the template sets *own* property of the instance. You can check it out in the original version, that `el.hasOwnProperty("count") returns `true`. However, it should not set it by `Object.defineProperty()` (as it has to do it, otherwise it would work).

If you switch the order of the definition, the `<simple-counter>` is already defined when the polymer element template is compiled, and then it works properly.

**Comment by dobexx** [comment]
Thanks for the quick answer.

In our infrastructure we do not use webpack or rollup, many things are loaded dynamically. A shift of hybrid elements to the front is not feasible for us.

Hmm we did not have this constellation when using lit elements at the same places.

There is certainly another possibility that certain elements will receive a custom element upgrade at a later date?

**Comment by smalluban** [comment]
I came up with an idea, that possibly fixes that behavior. Still, it's not a bug, but it happens when template engine sets properties before element is upgraded (that's the behavior of the example).

I'll let you know after the weekend.

**Comment by dobexx** [comment]
Great @smalluban . Robustness for such a constellation especially for large area dynamic loading of modules / components is not to be denied.

I just followed yours for the example and changed the order.

Now there is still a strange behaviour. If I now click on "Set 66 to Polymer property for passing", the value 66 is not regularly passed on to this.polyCount and thus to the count property.

Is this also related to this?

**Comment by smalluban** [comment]
> Now there is still a strange behavior. If I now click on "Set 66 to Polymer property for passing", the value 66 is not regularly passed on to this.polyCount and thus to the count property.

It is related to another template engine behavior (the hybrids template engine works the same). The Polymer component compares the last value of its own property to the next value, for example, set by the assertion. If the hybrids component count property might be changed by itself, the polymer component still "thinks" that the last value is what was set by the assertion, which can be wrong. In that case, the polymer does not set again value `66` (if the polymer component had `66` value before).

**Comment by smalluban** [comment]
@dobexx I prepared a fix for the main issue. Please use codesandbox environment to test it out before the merge. You can find here ready to go editor with an updated version of the library: https://github.com/hybridsjs/hybrids/pull/115#issuecomment-626222753

**Comment by dobexx** [comment]
Sensational work in the short time. 👍👍 I bow to you. 🙇

It works great. I was able to transfer the change in the `define.js` directly into our development environment and successfully test it there as well.

> The main reason to do that is a performance boost. The template engine assumes that if the value did not change, it does not have to be updated. In the simplest words, if the value is controlled from outside, it should not be also updated from inside. What I remember about polymer, it tried to create full two-way binding (changes dispatches special DOM events), so the parent was notified about the change by the child. However, it was abandoned with LitElement (it has one-way data binding), and of course with elements created with other libraries.

Although I have been working with polymer and Lit** for years, I could have come up with it myself. Thanks for the advice.

**Comment by smalluban** [comment]
`v4.1.9` has been relesed with the fix ;)
