### ISSUE TITLE
Properties defined with custom get,set & connect functions doesn't set values when passed in through the html-tag of the custom Element

### ISSUE THREAD

**Issue by zunwebs** [hybridsjs/hybrids#119]
**It appears that  the properties created using user-defined get/set/connect method doesn't behave the same as the properties defined with direct-default literals , when it has to set the values passed from the html-tag. Can you guide on how to fix this**

I am having a custom-element defined (using hybrids.js type-script ), having 2 types of properties , 

1. Property with a primitive value assignment like :   `name: 'hyts Nav Button',`
2. Property with get,set and connect defined like : `x`

Code below 

```javascript

function setConCheck(host:HytsNavButton,newValue:string="Domnik",prevValue:strig){
  console.log("call in set host is:");
  console.log(host);
  console.log("call in set  newValue is:"+ newValue);
   
  console.log("call in set  newValue is:"+ prevValue);

  return newValue;
 
  
}
const getConCheck=(host:HytsNavButton,lastValue:string)=> {
  console.log("call in get: lastValue"+lastValue);
  console.log("call in get: host is");
  console.log(host);
  
  return lastValue}
function connectHytsNavButton(host:HytsNavButton,propname:string,invalidate:any){
  console.log("call in connect:");
  console.log(host);
  console.log("call in connect: host.x ="+host.x);
  //host.x="40";
}
export const HytsNavButton: Hybrids<HytsNavButton> = {
  name: 'hyts Nav Button', //property with direct primitive literal assigned value
  concheck:'',
  _x:"30",
   x: //property pointing to custom-defined get/set/connect
   {  
    get:getConCheck  ,
     set:setConCheck,
     connect:connectHytsNavButton
  },render: (host:HytsNavButton) => html` 
    <button class="hyts-nav-button-clickable" onclick="${hytsNavButtonclick}">
     Name:${host.name}  -concheck:${host.concheck}-x:${host.x}|
    </button> 
   `,
};

```
In the `Index.html` I am referring the custom element as below: 
        `<hyts-nav-button name="Studio" concheck="ckstd" x="y"slot="nav-button-right"></hyts-nav-button>`  

What I would expect is the way the name value of **"Studio"** is picked up set on the name-property of the custom-element and then subsequently rendered on the html through the render fuction, the value assignment of "x" throught the custom-elements html tag "<hyts-nav-button>" should also behave the same way, however I don't it happening. 
The value of `x` always appears to be `undefined` and it dosen't get assigned the value of `y` that I have passed from the html tag `<hyts-nav-button name="Studio" concheck="ckstd" x="y"slot="nav-button-right"></hyts-nav-button>`. 

However if I set the value of x using `host.x="40" in the `connect--> connectHytsNavButton` function, then it reflects back on the html and appears to start binding well . 

Also the `console log` of host-element in `get,set or connect` methods appear as below : 
`<hyts-nav-button name="Studio" concheck="ckstd" x="y" slot="nav-button-right"></hyts-nav-button>`

 
**Please provide inputs to fix the issue**

P.S I am new to Hybrids js so I am be doing something wrong in the way the get/set connect functions I wrote. Please correct if any anomaly is detected.

**Comment by smalluban** [comment]
Hi @zunwebs!

As it might be confusing at first, the reason is really simple. One of the library foundations is the translation feature. It simplifies the definition, but after all, it is nothing more than using built-in factories for you (instead of using them directly).

For example, the following definitions are equal:

```javascript
import { property } from "hybrids";

const MyElementImplicit = {
  x: "30",
};

const MyElementExplicit = {
  x: property("30"),
};
```

Notice the use of the `property` factory. This is the place, where the feature of reading values from attributes is defined. The property factory returns an object with the definition of the property. If you define property directly, the definition includes only the code you wrote, so there is no feature of the `property()` factory.

However, the `property()` factory is flexible. The first argument might be a function (for transforming the value), and the second for `connect` method. You can use it directly like this:

```javascript
import { property } from "hybrids";

function transform(value) {
  return JSON.parse(value);
}

const MyElement = {
  x: property(transform, function connect(host, key, invalidate) {
    // do something
  }),
};
```

**Comment by zunwebs** [comment]
Hi @smalluban  , thanks for the response , explains the reasoning for the behaviour. 

However in this case I would like to understand ,
1) How is the ` "transform" function `different from `get/set`, and what dose it correspond to (get or set) ? 

2) The difference between the 2 constructs of defining a variable, and when to use which of these:
1) ```
 x:
   {  
    get:getConCheck  , //custom functions
     set:setConCheck, //custom functions
     connect:connectHytsNavButton //custom functions
  }
```
2) 
```
function transform(value) {
  return JSON.parse(value);
}
  x: property(transform, function connect(host, key, invalidate) {
    // do something
  }),
```

**Comment by smalluban** [comment]
The `transform` is a part of the `property` factory API. The first argument of the factory is a `defaultValue`. The factory can take a transform function from the type of the passed value. For example, if the value is a string, the `String()` function is used every time you **set** the value. It means, that you have a strict type of value. If you pass a number, it still will be a string.

If you want more control, you can pass a function as the first argument. Then, you have all of the control of what is the result of **setting** property value. It also includes taking the value from the attribute (The attribute fallback support). It means, that when the property is initialized (in the connect method) it takes the value from the corresponding attribute and passes is as `host[key] = value` (so implicitly uses the transform function). 

You can read more about it in the [property factory section](https://hybrids.js.org/built-in-factories/property#transform) of the documentation. There is an example of using `moment` library for the dates.

However, when you use direct construction with get/set methods, like `{ get: ..., set: ... }`, you are creating the property from scratch. It means, that it only does what you will put there. The `property()` factory is just generating that form for you with the features described above. For example, the library provides also children/parent factories, which do something totally different, and those properties are not connected to attributes at all.

**Comment by smalluban** [comment]
Feel free to re-open if you'll have other questions about the subject.
