### ISSUE TITLE
DOM Transclusion

### ISSUE THREAD

**Issue by benash** [hybridsjs/hybrids#120]
Thank you for this lovely library.

How can I perform "transclusion" in a component, i.e. render a components children like React's `props.children`? Using `innerHTML` (unsurprisingly) doesn't work.

```js
  define('my-title', {
    render: ({ innerHTML }) => html`
      <h1 class="uppercase">${innerHTML}</h1>
      `
  })
```

```html
<!-- the strong tags are escaped as opposed to becoming part of the DOM -->
<my-title>welcome to this <strong>awesome</strong> site</my-title>
```

**Comment by benash** [comment]
I now see this is possible:

```js
html`<h1 class="uppercase" innerHTML="${innerHTML}"></h1>`
```

Is this the recommended approach here?

**Comment by smalluban** [comment]
Hi @benash. The library follows the HTML standards, so it uses [Shadow DOM](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM) specification for DOM distribution, style encapsulation and more. The `render` factory (used by default when a function is set as `render` property) creates a `shadowRoot` and render the template there (you can omit the Shadow DOM by specifying options object, you can read more in the [render](https://hybrids.js.org/built-in-factories/render) section of the docs).

In your case, you can use the `<slot>` element, which indicates where the children from the light DOM should be placed in your Shadow DOM. It has builtin `slotchange` and other events. Also, it can be named, so you can have multiple slots inside. 
I can recommend following articles about it

* https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_templates_and_slots#Adding_flexibility_with_slots
* https://developers.google.com/web/fundamentals/web-components/shadowdom#composition_slot

Then your `<my-title>` component will look like this:

```javascript
const MyTitle = {
  render: () => html`
    <h1 class="uppercase">
      <slot></slot>
    </h1>
  `.style(`
     :host { display: block }
     h1.uppercase { ... }
   `),
};
```

Take into account that Shadow DOM encapsulates styles, so they only apply to code inside of the Shadow DOM (it is also explained in the linked above articles).

**Comment by benash** [comment]
Got it, `<slot></slot>` it is. 

I did notice that styles were being encapsulated as well, as for that reason, I'm currently also passing `{ shadowRoot: false }`. It seems there's some tension between the web components standards and the current trend of utility/functional CSS like Tailwind.

Thanks for the prompt response.

**Comment by smalluban** [comment]
> It seems there's some tension between the web components standards and the current trend of utility/functional CSS like Tailwind.

The CSS frameworks were designed before the Shadow DOM was created. Even now, they have a different purpose, so usually, they provide one single CSS file with all of the rules, which the user adds at the document level. The shadow DOM gives great flexibility of adding pieces of HTML nodes, which don't break any existing CSS code of the page. However, it must work in both ways, so the internal part of the web component then must have all of the required styles. 

If the CSS framework is built in modular way, usually it is possible to take out only those parts which are required for specific element like h1.uppercase in your case. 

In my code example I have used a recent addition to the library. If you use `style` helper, it uses Constructable Stylesheets when they are supported, so you don't have to worry about the performance of adding styles to each element.

**Comment by benash** [comment]
> The CSS frameworks were designed before the Shadow DOM was created.

It's interesting because Tailwind, which seems like the hottest new CSS library out there right now, only reached [v1.0](https://github.com/tailwindcss/tailwindcss/releases/tag/v1.0.0) in May 2019, but it (respectfully) seems to have [no notion of compatibility](https://github.com/tailwindcss/tailwindcss/issues/1298#issuecomment-580256808) with Shadow DOM. But my use case is development of a self-contained web app, not shareable components. So maybe I'll be fine keeping the Shadow DOM disabled for now.

> If the CSS framework is built in modular way, usually it is possible to take out only those parts which are required for specific element like h1.uppercase in your case.

This would seem like a rather painful approach to take with these utility-first libraries, which have so many generated rules (thousands). The best practice with normal DOM is to pull in what you need and then let a [purge utility](https://purgecss.com/) remove everything you don't seem to need. Seems there's again tension/conflicting interests here.

> If you use style helper, it uses Constructable Stylesheets when they are supported

This looks promising and would seem to save the day for Tailwind, etc. once browser support arrives.

**Comment by smalluban** [comment]
I think it is possible to use Tailwind with the library. It might only require additional setup. I checked it out on the codesandbox, but  I can't create here a custom webpack/parcel configuration. As you can see there (https://codesandbox.io/s/hybrids-web-component-with-tailwind-css-framework-766tb), the only requirement is that all of the required styles are inside of the Shadow DOM. You can manage your bundle configuration, that it will process the tailwindcss postcss plugin and at the end, you should use `raw-loader` to load CSS content (instead of applying it to the document by `style-loader`). 

Then you can create your styles like this: 

```css
@tailwind base;
...

.myTitle {
  @apply uppercase;
}
```

```javascript
import html from "hybrids";
import styles from "./myStyles.css"; // (it must contain text content of the CSS)

export default {
  render: () => html`
    <h1 class="myTitle">
      <slot></slot>
    </h1>
  `.style(styles),
};
```

You have two options - create one general CSS file (but I am not sure how then the Tailwind uses only subset of utilities), or create a CSS file for each component, but then you need to add `@tailwind base` to each file (as those rules are not shared between document and Shadow DOM).

However, there are still CSS properties that cross Shadow DOM boundary. Selectors are not shared, but all of the inheritable properties are - like colors, font styles, etc.. So if you set your main font for the document, it will be inherited by the Shadow DOM elements.

**Comment by benash** [comment]
> import styles from "./myStyles.css"

Importing like that seems to be the best approach for using Tailwind with hybrids + Shadow DOM at the moment. (I'd need to switch from `esbuild` to something with CSS text content support.)

Down the road, it seems like we want a styling system in which components have some knowledge of a theme as well as support for style props (the way [theme-ui](https://github.com/system-ui/theme-ui) does with React), but that can be used in conjunction with CSS custom properties to override values.

**Comment by smalluban** [comment]
Yep, the [CSS custom properties](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) are the answer for theming. There is also finally good support for the [`::part()` API](https://developer.mozilla.org/en-US/docs/Web/CSS/::part). This can also help with overwriting the styles from the Shadow DOM (overwriting the defaults).

**Comment by benash** [comment]
It turns out that doing something like this is also quite helpful for me:

```js
        .style('@import url("https://unpkg.com/tachyons@4.12.0/css/tachyons.min.css");')
```

I appreciate all the help!
