### ISSUE TITLE
How to reflow part of a component

### ISSUE THREAD

**Issue by galtenberg** [hybridsjs/hybrids#125]
This might be a request for documentation... I haven't been able to think out a solution given the current docs.

I have a component that shows pages in a carousel... one page at a time. Those pages are stored in data as an array of objects.

If I change the text of a page, I need to do some recomputation of later pages. 

When I recompute the array and set the property, the entire web page flashes as the pages are re-rendered. I have to then relocate the view to the page the user was on, which is another jolt in the user experience.

Really if it were possible to just update part of the array of objects (the pages after the current page the user is on), the user might not notice anything at all.

But since the object is frozen, I can't do something simple like `.splice()` the array to replace only later pages.

On twitter, you said the array needs to be a new array for cache invalidation. So even if I implement a custom factory or descriptor to get around the object freeze, it won't be of any use.

I tried to think of clever/boring ways of doing this, maybe splitting the data up into "pages that won't be recomputed" and "pages that will need to be recomputed", but regardless there's going to be a re-render / a flash in the UX.

I'd appreciate any ideas.

```javascript
// component
const NotebookView = {
  data: [{text: ""}, {text: ""}],
  currentPage: 1,
  intersect: intersectFactory(0),
  render: ({ data, currentPage }) => html\`
     ... data.map
         ... inner component, processes a single page object
             ... <p contenteditable="true" onblur="\${updateData}" innerText="\${data}"></p>

...

// simplified
async function updateData(host, event) {
  const view = document.querySelector('notebook-view')
  const currentPage = view.currentPage

  rawData = pullData()
  results = recompute(rawData, currentPage)

  // causes page to reflow
  view.data = results

  // since we've reflowed, we're away from the page we were on - scroll back to it - another jump in UX
  bringPageInView(view, 1, currentPage, true)
}
```

**Comment by smalluban** [comment]
The most obvious thing that comes to my mind are missing keys in the loop. The template engine supports setting keys for elements, so when they are re-ordered, or changed, they will be reused. Still not sure if it helps in your case, but you can add unique `id` property to your data in the array, and use it as the key of the element:

```javascript
const NotebookView = {
  data: [{ text: "", id: "1" }, { text: "", id: "2" }],
  render: ({ data }) => html`
    ${data.map(({ text, id }) => html`<p>${text}</p>`.key(id))}
  `,
```
If the data will be filtered, the correct ids will be reused instead of rendering them again.

More generally, I hope today or tomorrow I will merge and publish the store feature, which I was working over the year. You can read more here for now: https://github.com/hybridsjs/hybrids/tree/store/docs/store (the link will not work after merging to master). I think it might be helpful in your case, as it will be possible to create a model data for your pages and use it just like this:

```javascript
import { store } from "hybrids";

const Page = {
  id: true,  // the store generates UUIDv4 for client-side models
  text: "",
};

// Initialize some pages (or you can have them in some data source by `[store.connect]`)
store.set(Page, { text: "One" });
store.set(Page, { text: "Two" });

const NotebookView = {
  pages: store([Page]),
  render: ({ pages }) => html`
    ${pages.map(({ id, text }) => html`<p>${text}</p>`.key(id))}
  `,
};
```

**Comment by galtenberg** [comment]
Thank you very much for this.

I do have an `index` variable that filters down all the way to the lowest component, to act as the page number. I added that as `.key(index)` on every component `render`, and I still see the primary reflowing happening. But at least I know I'm using the template updating as efficiently as possible, and I can continue to think & look for the render logic that's causing the reflow.

I've been watching the `store` branch/PR, and have been very interested as to what it provides. I will give it a shot once merged. Thank you again!

**Comment by smalluban** [comment]
@galtenberg The store feature is live, so you might want to look at the [docs](https://hybrids.js.org/store/introduction) and try it ;)
