### ISSUE TITLE
Object references in render-templates does not re-render the element on value changes

### ISSUE THREAD

**Issue by zunwebs** [hybridsjs/hybrids#126]
**_Scenario:_**
I have a custom element **`"HytsNavBar"`** defined which contains a type-script-objects of type `Item` & `datax` and some primitive strings like `name` and `paramx` . These objects of  `Item` & `datax`  can infact be any complex objects with multiple fields of primitive and object types, e.g `Array/Map or other custom-types etc.`.  

I refer to my custom-elements primitive strings as well as the internal fields of these objects ( `Item` & `datax` ) in my html template. 
I see that only when the value of any primitive property of the custom-element changes the html is re-rendered ,however any change to the internal values of complex object types doesn't re-render the html. 
i.e any change to  HytsNavBar --> name or pramx ==> would trigger re-render. 
    any change to HytsNavBar --> itm.name or datax.x ==> would not trigger re-render. 

______________________________________________________________________________________________________
**_Code-References_**
```typescript
export class Item implements pele {

  constructor() {
  this.relationalElements=new Map<string,Map<string,pele>>();
  this.relationalSeqs=new Map<string,Map<number,string>>();

  this.fields=new Map();
 }
name:string='';
type:string='';
b_type:string='';
t_type:string='';
c_type:string='';
   uiid:string='';
   func_id:string='';
  id:uuid=null;
  seqId:number=-1;

   parentName:string="";
  parentType:string=""; // a code snipped of the class....
```

My custom element `HytsNavBar` refers to this class as below 

```typescript
interface datax{
    x:string;
    y:string;
}
interface HytsNavBar extends HTMLElement,StateSubComponent {
  name: string;
  itm:Item;
  itmId:string;
  rndr:any;
  parmx:string;
  datasz:datax;
}


// on Button click i change values 
export function hytsChangePNButtonclick(host: HytsNavBar,event:any) {
  let barItem:Item=store.state.get(host.itmId);
  if(barItem.parentName==undefined || barItem.parentName == ''){
  barItem.parentName="hytscomposer2";
  }else{
    barItem.parentName=barItem.parentName+'2';
  }
  store.dispatch('addItem', barItem.uiid,barItem);

}

// on connect of the cutom-element i subscribe to the changes of the values for the itm object. 
function getItemIdConnect(host:HytsNavBar){
  console.log("HytsNavBar^getItemIdConnect^Item in host of connected call back of configurable bar   :"+host.itmId);
  console.log(host);
  console.log("HytsNavBar^getItemIdConnect^Subscribing to statechange event");

 store.events.subscribe('stateChange', () => {
    console.log("hts-components^HytsNavBar^getItemIdConnect^value of state in hytsnavbar subscription is:");
    console.log(store.state);
    host.itm=store.state.get(host.itmId);
    // host.parmx=host.itm.parentName;  // ===>> * + * uncommenting this would trigger re-render of the html  * + * 
    // host.name=host.itm.parentName; // ===>> * + * uncommenting this would trigger re-render of the html * + * 
    host.datasz.x=host.itm.parentName;
    host.datasz.y=host.itm.parentName+host.itm.name;
    console.log("hts-components^HytsNavBar^getItemIdConnect^value of state in hytsnavbar subscription is: new datasz value is:");

    console.log(host.datasz);
    
});
  
}
```
And the render-template refers to the elements of this `"Item"` class and another interface `datax` as below : 
```typescript
return  html`  

     <div class="nav-toolbar"> ${host.itm} 
        <span style="margin-left:2vw" > ${host.name} [[(({{ ${ host.itmId}}}))][[[parmx:${host.parmx}]]]] </span> 
        <span style="margin-left:2vw" > [[${host.itm.name}]]  [[${host.itm.parentName}]]  </span>
        datasx value is {{{ ${host.datasz.x}}}} {{{ ${host.datasz.y}}}}
         <slot name="nav-button-left" style="margin-right:2vw"></slot> 
          <span class="spacer"> </span>
         <slot name="nav-button-right" style="margin-right:2vw"></slot>   
           <span class="spacertostart"> </span>
        <button onclick="${hytsChangePNButtonclick}">changehostname</button>
     </div>` 
```
Please note : the code is verified to be subscribing and reflecting the data changes in the **`"itm"`** object correctly. 
_____________________________________________________________________________________________________

**_Expectation :_** 
The expectation is that any change to to the host.itm.name / host.itm.parentName / host.datasz.x should also re-render the html. 

Please point me to something that I am missing of if my expectation of the behaviour is not correct

**Comment by zunwebs** [comment]
An Observation found is : Even if i have a single primitive- field which is getting rendered as part of the html-template, any event causing a change in the field is triggering the re-render, however there might be cases where, only the reference-fields composed inside an object hierarchy and which are rendered in the html templates are getting changed but noen-of the primitive fields are changing.

**Comment by smalluban** [comment]
Hi @zunwebs. It's hard to read your code example, but I think that I understand your concerns. The cache mechanism of the library is based on an equality check. By the design, you must update properties with new references, so updating the nested properties of the object is not supported (it won't trigger re-render). However, when template updates, it will pass all of the new values, so if you have changed nested object and other properties, it might be updated as well (but only by chance).

You can read more in the documentation [here](https://hybrids.js.org/core-concepts/descriptors#get):

> Cache mechanism uses equality check to compare values (nextValue !== lastValue), so it enforces using immutable data, which is one of the ground rules of the library.

However, from a few days, the new [`store` feature]() is available in the library, which covers your needs. The models can have nested structures, and after the change, they produce a new version of the instance (they are immutable). 

You can use the store like this:

```typescript
import { store, html, Hybrids, Model } from "hybrids";

interface Pele {
  ...
}

const Item: Model<Pele> = {
  some: {
    other: "",
  },
  data: [{ x: "", y: ""],
};

...

const MyElement: Hybrids<MyElement> = {
   items: store([Item]),
   render: ({ items }) => html`
     ${items.map(item => ... )}
   `,
}
```

**Comment by zunwebs** [comment]
Thanks for directing to the references @smalluban , it had been quite a while when I had started to implementing this feature , however, the store-features appears to be intresting and promising, would surely look into it and follow through the documentaiton on hybrids-store/model .

**Comment by smalluban** [comment]
Feel free to re-open if you will have any new questions about the issue.

**Comment by zunwebs** [comment]
Hi @smalluban  , 
I tried using the store feature where I could set and retrieve values from for the `item`  variable however the store ends up returning the same value for all the instances of the web component . 
So anywhere and everywhere the the web-component is used on the page , the same value of item reflects. 
I think I am doing something wrong with manipulating the value .
1. I had an id (uuid) field already on the Item model which I had to comment since hybrids errored out . And I understand that hybrids will auto assign it for each object added to the store . 
2. To update the value of item in the store I just use store.set(item,{ item properties with new values}) 
3. However with this I am unable to figure out as to 
3.1 : will the store have only 1 instance of the item value (for all instances of the web component being loaded) 
3.2 if in case if has different instances , how to access the particular instance of item from the store which was created in the store  for the web-component instance in question, since the  id is auto populate by hybrids there is no reference to it for me in the host for track if for pushing an update on the same instance of item in the store . 
Please let me know if I am missing on any documentation/concepts that I should've referenced
