### ISSUE TITLE
Component in component two word attribute use differences?

### ISSUE THREAD

**Issue by techninja** [hybridsjs/hybrids#129]
Hey again! Just wanted to say again how happy I am with Hybrids as I continue to use it to build out as many projects as I can. I did have a question about attributes which might be a little confusing, but hopefully I can describe it correctly.

Say you have a component with a two word camel case attribute 'myColor'.
```javascript
const innerComponent = {
  myColor: 'default',
  render: ({ myColor }) => html`
    Color is ${myColor}.
  `,
};

define('inner-component', innerComponent);
```

This is cleanly expanded to a hyphen separated attribute format, which works great in HTML here:
```html
<inner-component my-color="blue"></inner-component>
```

Now lets embed this into another component that passes a string in.

```javascript
const outerComponent = {
  outerColor: '',
  render: ({ outerColor }) => html`
    <inner-component
      my-color="green"
    ></inner-component>
  `,
};

define('outer-component', outerComponent);
```

With the following HTML.
```html
<outer-component></outer-component>
```

Then, in the console:
```javascript
const innerEl = document.querySelector('outer-component').shadowRoot.querySelector('inner-component');
innerEl.myColor
> "green"
innerEl.getAttribute('my-color');
> "green"
```

This works great, and has no problems. But as soon as we pass a value in through templating, changing out the render with the following:

```javascript
...
  render: ({ outerColor }) => html`
    <inner-component
      my-color=${outerColor}
    ></inner-component>
  `,
...
```

And adjust the HTML to bring in a value.
```html
<outer-component outer-color="blue"></outer-component>
```

This does not work. Well, it works halfway at least. In the console:
```javascript
const innerEl = document.querySelector('outer-component').shadowRoot.querySelector('inner-component');
innerEl.myColor
> "default"
innerEl.getAttribute('my-color');
> "blue"
```

Is this wrong? If we examine the element here, within innerComponent code `host.myColor` doesn't have a value unless we pass a string directly as `my-color="blue"`, but it does seem to be set correctly via string template if we use the camelcase attribute directly in the template. Should any attribute value of a nested component set via template code use the camelcase attribute? Is this a bug?

**Comment by smalluban** [comment]
Hi! The template engine supports properties, so you should use 

```javascript
html`<inner-component myColor="${outerColor}"></inner-component>`
```

inside of the outer component. It is explained in the docs here: https://hybrids.js.org/#/template-engine/properties-and-attributes?id=attribute-fallback ;)

The attribute fallback in the property factory is for end-user support (which uses the element inside of the HTML document). The fallback sets the value only once when the element is connected to the DOM. The only way to set dynamic value is by the property.

**Comment by techninja** [comment]
Ok that makes sense, I must have missed it. Thank you so much for the fast response!
