### ISSUE TITLE
How to fetch store model data after user's click action

### ISSUE THREAD

**Issue by pizitai** [hybridsjs/hybrids#130]
```javascript
const Movie = {
  id: true,
  title: "",
  ...,
  [store.connect] : {
    get: (id) => movieApi.get(id),
    list: ({ query, year }) => movieApi.search({ query, year }),
  },
};

const MovieList = {
  query: '',
  year: 2020,
  movies: store([Movie], (host) => ({ query: host.query, year: host.year })),
  render: ({ query, year, movies }) => html`
    <input value="${query}" oninput="${html.set("query")}" />
    <input type="number" value="${year}" oninput="${html.set("year")}" />
    <ul>
      ${store.ready(movies) && movies.map(movie => html`<li>...</li>`)}
    </ul>
  `,
}
```

**Comment by smalluban** [comment]
Hi @pizitai. Honestly, I didn't have time for creating more live examples for the store. For now, you can look at this example, which fetches user data: https://codesandbox.io/s/store-user-web-component-built-with-hybrids-library-dldtv?file=/src/StoreUser.js

However, the `movieApi` is just a container for the functions, which return some data from the API. It could be something like this:

```javascript
export function get(id) {
  return fetch(`https://my-moview.api/movie/$[id}`).then(res => res.json());
}

export function search({ query, year }) {
  return fetch(...).then(res => res.json());
}
```
```javascript
import * as movieApi from "./movieApi";
```

The store storage functions can return a Promise, or data.

**Comment by pizitai** [comment]
> Hi @pizitai. Honestly, I didn't have time for creating more live examples for the store. For now, you can look at this example, which fetches user data: https://codesandbox.io/s/store-user-web-component-built-with-hybrids-library-dldtv?file=/src/StoreUser.js
> 
> However, the `movieApi` is just a container for the functions, which return some data from the API. It could be something like this:
> 
> ```js
> export function get(id) {
>   return fetch(`https://my-movie-api.com/movie/${id}`).then(res => res.json());
> }
> 
> export function search({ query, year }) {
>   return fetch(...).then(res => res.json());
> }
> ```
> 
> ```js
> import * as movieApi from "./movieApi";
> ```
> 
> The store storage functions can return a Promise, or data.

@smalluban ### First thank you for your prompt reply

I have seen you above [example](https://codesandbox.io/s/store-user-web-component-built-with-hybrids-library-dldtv?file=/src/StoreUser.js:965-972).

## Maybe I didn't describe my problem clearly，  my problem is how to use list store；


### problem 

The business scenario is to click a button, send an HTTP request, and then return an array of data. Is there such an example? I hope you can help me, thank you.

**Comment by smalluban** [comment]
> The business scenario is to click a button, send an HTTP request, and then return an array of data. Is there such an example? I hope you can help me, thank you.

Now you've got my attention ;) As you may know the library forces declarative way as much as possible, so you can avoid procedural code - like, an action, which then fetches data and displays them. However, you may have a valid real-world scenario. However, other principles of the library can help you with that. One of the ground rules of the library is that properties are fetched only if they are referenced, so even if you define the property set as a store model, it will be fetched only if the property is used. Taking that in mind, you can create another property, which conditionally returns the model if your "switch" is turned on. You can code it just like that:

```javascript
import { store, html } from "hybrids";
import MyDataModel from "./MyDataModel.js";

function switchClick(host) {
  host.isClicked = true;
}

const DisplayData = {
  isClicked: false,
  data: store([MyDataModel]),
  displayData: (host) => host.isClicked ? host.data : null,
  render: ({ displayData }) => html`
    <button onclick="${switchClick}">Fetch data</button>
    ${store.ready(displayData) && ... }
  `,
};
```

It is important to not use destructuring in `displayData` getter, as then `data` would be fetched regardless of the condition.

There is also another way. If you don't need some built-in features of the `store` factory, you can use `store.get()` method directly:

```javascript
const DisplayData = {
  isClicked: false,
  data: ({ isClicked }) => isClicked ? store.get([MyDataModel]) : null,
  render: ({ data }) => html`
    ${store.ready(data) && ... }
  `,
};
```

**Comment by pizitai** [comment]
> > The business scenario is to click a button, send an HTTP request, and then return an array of data. Is there such an example? I hope you can help me, thank you.
> 
> Now you've got my attention ;) As you may know the library forces declarative way as much as possible, so you can avoid procedural code - like, an action, which then fetches data and displays them. Still, you may have a valid real-world scenario. However, other principles of the library can help you with that. One of the ground rules of the library is that properties are fetched only if they are referenced, so even if you define the property set as a store model, it will be fetched only if the property is used. Taking that in mind, you can create another property, which conditionally returns the model if your "switch" is turned on. You can code it just like that:
> 
> ```js
> import { store, html } from "hybrids";
> import MyDataModel from "./MyDataModel.js";
> 
> function switchClick(host) {
>   host.isClicked = true;
> }
> 
> const DisplayData = {
>   isClicked: false,
>   data: store([MyDataModel]),
>   displayData: (host) => host.isClicked ? host.data : null,
>   render: ({ displayData }) => html`
>     <button onclick="${switchClick}">Fetch data</button>
>     ${store.ready(displayData) && ... }
>   `,
> };
> ```
> 
> It is important to not use destructuring in `displayData` getter, as then `data` would be fetched regardless of the condition.
> 
> There is also another way. If you don't need some built-in features of the `store` factory, you can use `store.get()` method directly:
> 
> ```js
> const DisplayData = {
>   isClicked: false,
>   data: ({ isClicked }) => isClicked ? store.get([MyDataModel]) : null,
>   render: ({ data }) => html`
>     ${store.ready(data) && ... }
>   `,
> };
> ```

### Thank you for your reply.

I focked you example https://codesandbox.io/s/store-user-web-component-built-with-hybrids-library-dldtv?file=/src/StoreUser.js

I modify some file generate my example, below is 
https://codesandbox.io/s/store-user-web-component-built-with-hybrids-library-forked-metto?file=/src/StoreUser.js:845-849

There is something wrong in my example。

Can you help me.

**Comment by smalluban** [comment]
It looks that you have found a bug ;) I looked, and I missed tests for the list option with parameters. I will prepare a fix as soon as possible.

**Comment by smalluban** [comment]
I released a new version and fixed your example. Here you have my version: https://codesandbox.io/s/store-user-web-component-built-with-hybrids-library-forked-epr1m?file=/src/StoreUser.js

There were a few other problems, the model did not have `first_name` and `last_name` values. The list method was taking the page as an argument, not an object, so I had to remove destructuring there.

**Comment by pizitai** [comment]
> I released a new version and fixed your example. Here you have my version: https://codesandbox.io/s/store-user-web-component-built-with-hybrids-library-forked-epr1m?file=/src/StoreUser.js
> 
> There were a few other problems, the model did not have `first_name` and `last_name` values. The list method was taking the page as an argument, not an object, so I had to remove destructuring there.

Thank you very much for your help. Your reply means a lot to me and makes me have a great interest in this library. 

## Thank you again!
