### ISSUE TITLE
Expose a way to hook into the reactivity system

### ISSUE THREAD

**Issue by bennypowers** [hybridsjs/hybrids#131]
Hey there!

So my use case is to ship a factory `query` that, when set on the `query` property, mixes in some graphql code to the final class.

I'd like that factory to *also* add some sibling properties to the class, especially `data`.

Here's my solution so far: https://github.com/apollo-elements/apollo-elements/blob/1ce5c90a5dd5726984e37a8dffe4e5a3845dd792/packages/hybrids/helpers/prototypes.ts#L69-L90

Not great, since `hybrids/esm/cache.js` is, as far as I can tell, private.

**Comment by smalluban** [comment]
I would avoid creating a plugin, which requires more than one property set of the element definition. Then, a user does not see explicitly what properties are defined in that element. However, it is rather simple to create a factory, which returns a list of properties (descriptors) instead of one property:

```javascript
function myMultipleFactory(options) {
  return {
    one: "",
    two: 2,
    three: {
      get: () => ...,
      set: () => ...,
    },
  };
}

const MyElement = {
  ...myMultipleFactory({ optionOne: false }),
  render: ({ three }) => html`<div>${three}</div>`,
};
```

Still, you have to see major disadvantages, like not be able to set more than one property of that factory in the element, or implicit usage of the property.

**Comment by bennypowers** [comment]
Thanks for writing back. I appreciate where you're coming from Dominik, and I think from a purely-hybrids-oriented perspective that would be ideal, but if I understood what you're suggesting correctly, I don't think it will work in my case, even putting aside my concerns about maintenance burden.

For me, one of the biggest advantages of functional programming is that it encourages the use of common interfaces. This is also one of the things which drew me to web components.

If I did as you suggest, and hid all of those properties (`data`, `error`, etc) behind single props (e.g. `query`), then not only would the maintenance and testing burden for hybrids-based query components be much higher than for other libraries, but their public APIs would be highly divergent as well.

```js
const litEl = document.createElement("lit-apollo-query"); // LitElement-based
const fastEl = document.createElement("fast-apollo-query"); // FASTElement-based
const vanillaEl = document.createElement("html-apollo-query"); // HTMLElement-based
const hybridsEl = document.createElement("hybrids-apollo-query"); // Hybrids-based

for (const el of [litEl, fastEl, vanillaEl, hybridsEl])
  runPublicAPITests(el, SomeQuery);
```

This would pass for all cases except hybrids, whereas with my approach it passes for hybrids as well. In other words, using my above hack, users can swap out their implementation as desired, because the public interface is shared.

-----

I'll admit this is an uncommon use case for Hybrids, and users who are all-in should avoid playing with the library's guts when building app components, but Apollo Elements is library code.

I hope you'll reconsider adding in some facility to accomplish this. It would be enough to explicitly export (and type) the `cache`, so users could:

```ts
interface HookHybridsOptions<T> {
  host: T,
  key: keyof T|string,
  init: unknown
}

export function hookIntoHybridsRender<T>(opts: HookHybridsOptions<T>): void {
  const { host, init, key } = opts;
  const config = property(init);
  Object.defineProperty(host, key, {
    enumerable: true,
    configurable: true,
    get() {
      return cache.get(host, key, config.get);
    },
    set(newValue) {
      cache.set(host, key, config.set, newValue);
    },
  });
}
```

I'm not particular about the specific API for *how* I can programmatically add observed properties, I just need a "blessed" way that I *can*.

```js
import { addDescriptor, property } from 'hybrids';

/** 
 * Adds the property "sneaky: string" as an observed property on the host
 */
function mySneakyFn(host) {
  host.addDescriptor('sneaky', property('hah!');
}
```

**Comment by smalluban** [comment]
I understand your point of view of creating a unified public API regardless of the library. Still, what I was trying to tell you was that you can create a factory with multiple properties without "hacking" the internals of the hybrids ;)

I know that it still might require a different implementation, but you can create your API the same, as for other libraries. You can create a factory, which returns a map of properties, which are then spread on the component definition as I showed in the code example in my previous comment.

**Comment by bennypowers** [comment]
Thinking that some code might help spur discussion I created #139. I'm sure there are some small details to work out there, but if merged, this would more than satisfy my requirements.

**Comment by bennypowers** [comment]
It would still be cool to have this for more advanced cases, but I won't be pursuing this approach any more in `@apollo-elements/hybrids`, there will be one or two breaking changes instead

**Comment by smalluban** [comment]
For now, the cache is an internal part of the library, mainly because of The raw API and ability to make changes without external API breaking changes. As I wrote some time ago, in your case, it's still possible to write it without direct access to the cache mechanism. It's more your choice to have one shared mixing. I know that it might be problematic, but opening internal might course more damage.

Nevertheless, thanks for the discussion and for your time creating a PR :)
