### ISSUE TITLE
Condition attributes of a NodeElement

### ISSUE THREAD

**Issue by ErickTucto** [hybridsjs/hybrids#132]
```javascript
import { getUser } from './redux/user.js'

const handleChange = (host, { target: { value } }) => host.value = value
const handleSearch = (host, evt) => {
  host.loading = true
  getUser({
    search: host.value
  })
}

const Search = {
  loading: false,
  value: '',
  render: ({ loading }) => html`
    <input type="text" onchange="${handleChange}"/>
    <button type="button" onclick="${handleSearch}" ${loading ? 'disabled' : '' }>search</button>
  `
}
```

**I want to disable the button when making the request**

But in the DOM the following is observed

![imagen](https://user-images.githubusercontent.com/22831024/98715724-8aefd600-2358-11eb-94d0-3598b453b141.png)

The error is very similar to issue #124

**Comment by smalluban** [comment]
Hi @ErickTucto! Sorry for the late response, but I was busy lately. Setting attributes/properties like in your example are not supported by the library. The expression is only allowed as element content, or element attribute value. Still, you can easily set `disabled` property of the Button. As you may know, for all of the built-in elements, all of the attributes have corresponding properties. The template engine supports setting boolean values. You can simply write your template like this:

```javascript
...

const Search = {
  loading: false,
  value: '',
  render: ({ loading }) => html`
    <input type="text" onchange="${handleChange}"/>
    <button type="button" onclick="${handleSearch}" disabled="${loading}">search</button>
  `
};
```

The most important change is with `disabled="${loading}"`. And yes, it is that simple ;)

**Comment by ErickTucto** [comment]
Thank you very much you are right, it is disabled correctly
