### ISSUE TITLE
There is something wrong with className which write with react

### ISSUE THREAD

**Issue by pizitai** [hybridsjs/hybrids#134]
Hi，I want use hybrids with react. When I write a css, and import it to js. It seems not work.
My fork url is https://codesandbox.io/s/react-counter-web-component-built-with-hybrids-library-forked-mvj8v
1、First step
I fork a project from https://hybrids.js.org/#/core-features/render
As shown in the following figure.

![dd](https://test-pizitai.oss-cn-beijing.aliyuncs.com/github/1605495583%281%29.jpg?x-oss-process=style/watermark)

2、I add a `index.css`
3、In `Counter.jsx`
```js
import styles from "./index.css";


<button className={styles.a} onClick={() => setCount(count + 1)}>
      Count: {count}
    </button>
```

4、The result is className is not work

**Comment by smalluban** [comment]
Hi @pizitai! Are you sure, that `className` does not work? When I open your fork everything seems to work properly:

![Screenshot 2020-11-16 112318](https://user-images.githubusercontent.com/1906677/99241417-23290780-27fe-11eb-924e-ad0bdabca2a4.png)

**Comment by pizitai** [comment]
Thanks，It works fine
