### ISSUE TITLE
Trouble integrating x-state

### ISSUE THREAD

**Issue by adam-cyclones** [hybridsjs/hybrids#135]
Hello, thank you for this wonderful project I am very keen to adopt it but there is one snag... I use xState to control state, the closest analogue to xState is the Redux examples given on the docs, I think It should be possible to use some state management via the Actor model and state machines, I am so close but Im stuck with the cache invalidate perhaps.

I have wrote an example that forks a working redux example:
https://codesandbox.io/s/beautiful-hill-s34uf?file=/src/redux-counter.ts

You can see that when the state machines state (known as context) changes, the web component does update, but only once, I can no longer increment the count.

I understand this is a third party issue, but any help would be amazing!

**Comment by smalluban** [comment]
Hi @adam-cyclones! Thanks for the nice words about the library. I'll try to help as much as I can. I have to say, that you have chosen a complicated library for managing the state. It took me like ten minutes to figure out where to look in the docs to understand what is all about (even though I read before about xState).

If you really need persistent states, where you go from one to another, it should be a way to go. However, if you look for a redux replacement, I suggest looking at the [store](https://hybrids.js.org/#/store/overview) feature of the library.

Ok, back to your problem. Hybrids works fine, you have a bug in the connectMachine function:

```javascript
const get = () => {
  // instead "machine", it has to be "state"
  return interpreter.state.context[key];
};
```

The second problem is with the result of the subscribe method. It returns an object with the `unsubscribe` method (Why it does not return a function...).

Here you have my fork of your fork ;) - https://codesandbox.io/s/hungry-mclean-b1ffg?file=/src/redux-counter.ts

If you would like to look at the store feature, here you have a fully working example with global state, which holds a count value and allow updating it outside of the component definition:

```javascript
import { store, html } from "hybrids";

const MyStore = {
  count: 0,
};

function inc() {
  const store = store.get(MyStore);
  store.set(MyStore, { count: store.count + 1 });
};

function dec() {
  const store = store.get(MyStore);
  store.set(MyStore, { count: store.count - 1 });
}

// it can be in a separate file importing store and actions

const MyElement = {
  count: () => store.get(Store).count,
  render: ({ count }) => html`
    Count: ${count}
    <button onclick={inc}>+1</button>
    <button onclick={dev}>-1</button>
  `,
};
```

However, it can be even easier if you allow direct manipulation. You can then use a store factory, and update the store in-place:

```javascript
const MyStore = {
  count: 0,
};

function inc(host) {
  host.myStore = { count: host.count + 1 };
}

function dec(host) {
  host.myStore = { count: host.count - 1 };
}

const MyElement = {
  myStore: store(MyStore),
  count: ({ myStore }) => myStore.count,
  render: ({ count }) => html`...`,
};
```

**Comment by adam-cyclones** [comment]
Oooooooh! I get it now thanks so much!

You got me, 😅 I knew about the built in store (kudos for that) and it's really hard to justify why I'm using xState but for a couple of reasons, xState is one of those libraries you have to try it out to see the reasoning.

 It's absolutely complex for just storing state and I'm afraid I kept it's purposes quiet because it's not so important what I want to do with it. 

If you see the xState visualizer you can see how all the logic is serializable which is just one use case checked for me.

None the less, thank you so much, I really enjoyed the talk about hybrids and il be sure to big up the library on my blog when I do a write-up.
