### ISSUE TITLE
Issue Applying Properties to Component Template on First Render

### ISSUE THREAD

**Issue by auzmartist** [hybridsjs/hybrids#138]
Hi @smalluban,
I've run across a rather bizarre bug which I'm hoping you may be able to take a look at.

I've prepared a fork of your simple-counter code sandbox explaining and demonstrating the problem:
https://codesandbox.io/s/simple-counter-web-component-built-with-hybrids-library-forked-ykorm

In short, I cannot assign `type="text"` to an input in the component template on the first render, but I can easily apply other property values (like `number`) at first render OR apply `type="text"` at any later point.

This is maybe one very specific example of a broader class of bug, but I have not run across any other instances. Hopefully not. Any insight?

**Comment by smalluban** [comment]
Hi @auzmartist. 

Actually, it's not a bug in the library, but rather not a standard behavior of the HTML. 

The template engine for the expressions as an attribute value tries to set property first, then it fallbacks to the attribute. All of the built-in elements have properties in sync with the attributes, so updating property updates also corresponding attributes. 

In your case, the input element by default has the type set to `"text"`. It means that the template engine does not set it, as it is already set to this value. This is why it starts working for a change from a different type. 

The real question is why the browser does not set input type attribute by default to reflect the value of the property...

**Comment by auzmartist** [comment]
😮 I didn't think of that but it appears to be the case. For any following along, the difference can be observed with the following two snippets:

What I'd expect the template engine to do:
```js
const el = document.createElement('input')
el.type = 'text' // or el.setAttribute('type', 'text')
document.body.appendChild(el) // renders <input type="text" />
console.log('property:', el.type, ' attribute:', el.getAttribute('type')) // prints "property: text  attribute: text"
```
What the template engine does:
```js
const el = document.createElement('input')
// no assignment here since 'text' is already the property value
document.body.appendChild(el) // renders <input />
console.log('property:', el.type, ' attribute:', el.getAttribute('type')) // prints "property: text  attribute: null"
```

In both cases, the property is `text` but the attribute is only set if explicitly assigned. This creates some unfortunate styling irregularities where you cannot trust that `input[type="text"]` will reliably select hybrids-rendered template code reading `<input type="text">` since the assignment will be skipped over.

I can see how removing the line you linked to would be problematic... but I also don't see a way to be assured that the property or attribute is assigned using the template engine. For these edge cases, do you see any utility in exposing a way to force the assignment? Perhaps something like:

```js
html`<input type="${type}"/>`.flags({force: false})
```

If the line you linked to is there for rendering performance reasons, I can imagine this could be cautioned against in the docs and mitigated in practice with template composition.

**Comment by smalluban** [comment]
The template engine works fine, as the value of the `el.type` is correct with current behavior. The input works as expected. The odd behavior is within the design of the HTML input element, which does not reflect the default value of the `type` property to the attribute. However, I would rather advise you to set styles using classes rather than attributes. It is super simple to change your template, so it will work fine: 

```javascript
const MyElement = {
  type: "text",
  render: ({ type }) => html`
    <style>.text { color: red } .number { color: blue }</style>
    <input class=${{ type }} type=${{ type }} />
  `,
};
```

I would like to not fix a bug, which is not a bug ;) And setting the same value for the element is redundant. Giving the option rather than creating a better default makes things more complicated. This is one of the ideas of the library - makes things simpler. If as a user I will have an option `force`, then I will start thinking where should I use it. However, the answer is - you don't have to... ;)
