### ISSUE TITLE
Is there a way to render sub html elements as standard HTML and not as a new shadowTree?

### ISSUE THREAD

**Issue by merianos** [hybridsjs/hybrids#140]
Hello,

I am new to Hybrids and I try to create a custom auto-select field that will allow the end user to perform a search using Ajax, and the results will be displayed in the drop down list, from which the user will be able to choose some options.

More or less, what I try to do is something like the Select2 but using only the hybrids.

So far, I have made a new element for the results list that is going to displayed below the search field. My code so far looks like that:

```js
const emptyList = host => !host.isEmpty ? "" : html`
    <div>This is empty</div>
`;

const notEmptyList = host => {
    if (host.isEmpty) {
        return "";
    }

    return host.options.map(
        (option, idx) => {
            let classes = [
                "cl-drop-down__option"
            ];

            if (-1 !== host.selected.indexOf(option.id)) {
                classes.push("cl-drop-down__option--selected");
            }

            if (idx === host.selectedIdx) {
                classes.push("cl-drop-down__option--current");
            }

            return html`
                <div 
                    className="${classes.join(" ")}" 
                    data-id="${option.id}"
                    data-text="${option.text}"
                >
                    ${option.text}
                </div> `;
        }
    );
};

export const ClDropDown = {
    isEmpty    : true,
    isOpen     : false,
    selectedIdx: {
        observe: (host, newValue, lastValue) => {
            let currentOption = host.querySelectorAll(".cl-drop-down__option--current");

            console.log("The Option Element: ", currentOption); // <----- This is always empty
        }
    },
    options    : {
        // ...
    },
    selected   : [],
    render     : (host) => html`
        ${style}
        <div class="cl-drop-down">
            ${emptyList(host)}
            ${notEmptyList(host)}
        </div>
    `
};
```
So, the problem I have with the code above, is that the `ClDropDown.selectedIdx.observe` function, returns always an empty `NodeList` although the host contains elements inside.

From what I found in my browser console, the actual problem seems to be that the items I query with the `let currentOption = host.querySelectorAll(".cl-drop-down__option--current");` are located in the shadowDOM.

So, is there a way to attach the new elements as not a nested shadowDOM ?

Thank you in advance ! :+1:

**Comment by merianos** [comment]
Hellow @smalluban .

I am impresses on how fast I got an answer to my question !!!

So, the reason I want to scan the DOM is because to know when a selected item is outside of the view area of the dropdown and scroll to that element.

For example, if the search result comes with 100 results, and the user press the up keyboard button to go directly to the last item of the results, I wan't the results contains to scroll down automatically in order to display the current selected item.

For the moment I don't have any other solution on how to achieve that, and I wanted to scan the DOM. If you have any better solution I am happy to listen :)

Anyway, thank you very much for your response and your assistance :)

**Comment by smalluban** [comment]
@merianos Feel free to re-open, if yo need some more help with the subject.
