### ISSUE TITLE
How to nest child components

### ISSUE THREAD

**Issue by benc-uk** [hybridsjs/hybrids#141]
I want to have my markup look something like this

```html
    <group-row>
      <midi-slider channel="13"></midi-slider>
      <midi-slider channel="4"></midi-slider>
    </group-row>
```

Where `group-row` is a very simple container component defined as follows
```js
import { html, define } from "https://unpkg.com/hybrids@^4/src";

export const row= {
  render: () => html`<div></div>`,
};

define("group-row", Component);
```

No matter what I do, I can't get the child elements (any I create) to render inside the group-row div, they just disappear.
If I put them in a plain HTML tag like a `div` then everything is fine, but this is NOT how I want to construct my app

This seems a very fundamental and basic thing to want to do but the documentation contains no examples of this and I'm stuck

**Comment by benc-uk** [comment]
I was missing `<slot> from the emaplet

**Comment by smalluban** [comment]
Hi @benc-uk. The Shadow DOM is a web standard, not a feature of the library itself. In the same way, as the docs don't explain how other elements or Web APIs work, the same is with the Shadow DOM. 

However, in the render factory section, you can find a link to `Shadow DOM` documentation from the MDN: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_shadow_DOM. There you can find a link to a specific article about slots: https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_templates_and_slots.

I am aware that Shadow DOM still might be new technology, but in time people will get used to it, and then explaining things that are documented in right place (web documentation) will not have to be documented in libraries, which use it.
