### ISSUE TITLE
CSS Classes not working when added to components

### ISSUE THREAD

**Issue by CodingJinxx** [hybridsjs/hybrids#142]
When using css styling as described in the docs, css classes seem to not work on components. I have created a [repository](https://github.com/CodingJinxx/hybrid-issue-css) with my code that shows the issue at hand. 
 
To start the project simply run `npm run-script dev` or to build `npm run-script build` when using node version v14.15.4 or later.

Here is the component where the css classes arent working
```js
import { html, define } from "hybrids";
import global from '../scss/stylesheet.scss';

export const Navbar = {
	brand: "",
	brandhref: "",
	render: ({ brand, brandhref }) => html`
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="${brandhref}">
                <img src="${brand}"></img>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav mr-auto"> 
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Features</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Pricing</a>
                    </li>
                </ul>
            </div>
        </nav>
    `.style(global),
};

define("main-navbar", Navbar);
``` 

DISCLAIMER: it might seem the issue is that i am import a .scss file, this .scss is changed to a .css by webpack after building

When running this project this is what the website looks like with the inspector

![2021-01-12 22_32_16-](https://user-images.githubusercontent.com/41790928/104376975-0ff89680-5526-11eb-8925-16a4b1dfd647.png)

Here the nav with the navbar class doesn't have the navbar class in the inspector. I'm not sure if I'm doing something incorrectly or if there is a bug. I tried following the docs as closely as possible.

**Comment by smalluban** [comment]
Hi @CodingJinxx! Please look at the styling documentation of the template engine - https://hybrids.js.org/#/template-engine/styling?id=css-stylesheet. The imported stylesheet must be a file content, not a file path, as it is now in your example. You are still loading styles in the head part of the document. For using inside of the Shadow DOM they must be passed there.

The docs also says about how to do it with webpack - use `raw-loader` after processing scss (sccs -> post-css -> css -> raw -loader). It will work then ;)

**Comment by CodingJinxx** [comment]
Oh sorry about that. I was using raw-loader but must have done it incorrectly then. Thank you for the help :)

**Comment by CodingJinxx** [comment]
It seems that i installed raw-loader but never actually used it.

**Comment by smalluban** [comment]
No problem :)
