### ISSUE TITLE
Problem using nested templates

### ISSUE THREAD

**Issue by benash** [hybridsjs/hybrids#145]
Hi, I am attempting to create a `styled` helper method that behaves like `html` but adds some default styling. The styling part itself works fine, but I'm getting an error related to an `onsubmit` callback. Here's what works:

```typescript
const handleSubmit = (host: NvForm, event: Event) => {
  event.preventDefault()
}

export const NvForm: Hybrids<NvForm> = {
  loading: false,
  render: () => html`
    <form onsubmit="${handleSubmit}">
      . . . 
    </form>
  `,
}
```

And here's what doesn't, throwing `Uncaught Error: Event listener must be a function: object`:
```typescript
function styled<E extends HTMLElement>(parts: TemplateStringsArray, ...args: unknown[]): hybrids.UpdateFunctionWithMethods<E> {
  return html`
    ${html(parts, args)}
    <style>
      @import "styles.css";
    </style>
  `
}

export const NvForm: Hybrids<NvForm> = {
  loading: false,
  render: () => styled`
    <form onsubmit="${handleSubmit}">
      . . . 
    </form>
  `,
}
```

**Comment by benash** [comment]
Oh, I now see the documentation on [nested templates for styling](https://hybrids.js.org/#/template-engine/styling?id=nested-template). OK, I assume that's the route I should take. But if it's possible to do what I was trying (to save a little bit of boilerplate), please let me know.

**Comment by smalluban** [comment]
Hi @benash, l think your code will work. `html()` takes a list of arguments, so you should spread the args into the nested html call (as three dots operator).

It's a clever idea, must say. However, you can simplify it a little bit. The result of the html call has a built-in style helper, so you can define your styled function like this:

```js
import styles from "styles.css";

function styled(parts, ...args) {
  return html(parts, ...args).style(styles);
}
```
Of course, the above solution requires a bundles, which can handle CSS files (it should CSS resolve to file content).

**Comment by benash** [comment]
Oh, perfect, the spread `...args` fixed it. I'll roll with that then. I'm not yet using a bundler (hoping to survive without one). But if I bite the bullet later on, I'll keep that style helper in mind. Thanks for the assistance and for this awesome project.

**Comment by smalluban** [comment]
I looked into the docs, and you can safely use `@import "style.css"` as a styles variable, so the code can look like this:

```js
function styled(parts, ...args) {
  return html(parts, ...args).style('@import "styles.css"');
}
```

On note - the file will be loaded relative to the current document address, not a js file, where you will use it. I recommend using an absolute path to the CSS like `"/assets/styles.css"`.

**Comment by benash** [comment]
That indeed works and is a welcomed improvement
