### ISSUE TITLE
Draft store throws "stale" error when updated by html.set on a range input

### ISSUE THREAD

**Issue by terrygonguet** [hybridsjs/hybrids#146]
I'm pretty new to Hybrids so it might be my fault but everything else I try works well so I can only assume the problem isn't on my end.

I have a singleton style store that is updated in draft mode in a form via `html.set` on a range input and it throws an `Provided model instance has expired. Haven't you used stale value?` error when using the `input` event.

```js
const Component = {
    level: store(Level, { draft: true },
    render: ({ level }) =>  html`<input
	type="range"
	min="10"
	max="50"
	defaultValue=${level.width}
	onchange=${html.set(level, "width")}
	oninput=${html.set(level, "width")}
    />`
}
```

When using only `onchange` it has no problem, no matter how fast I click but obviously doesn't reflect the value as you move the slider. 

Do I have to have annother temp variable to update on `input` and only update the store on `change`?

**Comment by smalluban** [comment]
Honestly, I did not test a range input. It looks that `input` events are triggered before the view is updated. Store set function is asynchronous, so only after promise resolves after the next animation frame your input will have a new listener generated by the html.set() helper. For text inputs, it works fine, even if you try to type super fast ;)

I might have a solution, which will remove that error at all, as the old obsolete model instance can reference a current one. Then using obsolete model for setting new values would use that current instance. Still, I need to test it, if it will work.

Thanks for sharing the problem. Stay tuned for updates.

**Comment by smalluban** [comment]
I've got good news. You can update hybrids to `v5.0.2` and your code should work fine (with the `input` event). Here you have a commit with the change: https://github.com/hybridsjs/hybrids/commit/2603bc094ba34d81bfab75cccae19204982f8c6d

Let me know if it works for you and if you need more help with the problem.

**Comment by terrygonguet** [comment]
I can confirm that it does indeed work now, thank you for the very fast fix!

Turns out it makes more sense for me to handle it another way but I'm enjoying Hybrids a lot, it has a very refreshing way of doing things 👍

This is good to close for me.
