### ISSUE TITLE
[React|Vue] How can i add a function to the web component?

### ISSUE THREAD

**Issue by jonathansantos-hotmart** [hybridsjs/hybrids#15]
I'm going to create a lib of ui.
I need components to receive events after React.js.

**Comment by jonathansantos-hotmart** [comment]
This lib will be used in a React.js app and a Vue.js app

**Comment by jonathansantos-hotmart** [comment]
![captura de tela 2018-10-16 as 14 45 02](https://user-images.githubusercontent.com/43818727/47036109-200c4a80-d152-11e8-9775-37e0a97f64d6.png)

**Comment by jonathansantos-hotmart** [comment]
![captura de tela 2018-10-16 as 14 47 10](https://user-images.githubusercontent.com/43818727/47036231-695c9a00-d152-11e8-9400-3b852a4acf41.png)

**Comment by smalluban** [comment]
I think your question is more about how can you create web components with hybrids, that easily integrate with React and Vue?

## React

Let's start with using custom elements in React. Unfortunately, it has one of the worst support (among the great frameworks) for using custom elements inside of the React components. Please, look at this links: 

https://reactjs.org/docs/web-components.html
https://custom-elements-everywhere.com/libraries/react/results/results.html
https://github.com/facebook/react/issues/11347

What does it mean? React only passes `string` values, and only as attributes (not as properties). You can't pass a function to custom property (it will be serialized to string value). However, it is still possible to use custom elements with a current version of React. There are projects, that wrap custom elements into the React components, so you can pass callbacks to custom events and set custom properties: 

https://github.com/webcomponents/react-integration#readme

## Vue

With Vue you have more luck :) It supports passing properties and can listen to custom events :)

## Building universal web components

Why I wrote about custom props and custom events? Your web component example showed me, that you tried to built it in the *react way*. You tried to pass method to property and then pass it to your internal element, which is a button in your example.

You should think about web components more like something that is not tied to any framework and any specific pattern. What we want to do is to use the platform. So, what it is in your case? 

You want, that your custom button can be listen to click event. Actually, it is already there without writing any line of code. Custom element is still an element, which inherites all native and supported events. If a user of your custom element clicks on it, it will dispatch "click" event, which can be listen. In your React code it could be done like this:

```javascript
render() {
  return <hot-button color="primary" onClick={this.handleClick} />
}
```

Notice the uppercase letter in "onClick" - this is a special React name for listening DOM events - and react only support a list of that events (that's way it so lame beacuse you can't listen to custom events just like that).

If you would create more sofisticated component, for example date picker, which should allow to listen when date is changed, you should not use for that properties but trigger custom event. For example:

```javascript
import { dispatchEvent, html } from 'hybrids';

function changeDate(host) {
  // do something with internal logic to change date
  host.date = 'new date';

  // Spread the news, that date was changed
  dispatchEvent(host, 'date-change');
}

const DatePicker = {
  date: 'today',
  render: ({ ... }) => html`
    <button onclick=${changeDate}>Change date</button>
  `,
}
```

Above example is simplified, but I think you can read the pattern from that. If the custom element should communicate with outside world, it should dispatch event (it is how the Web works with native elements).

### Footnotoes

I saw in your web component example, that you use dynamic styles - `${style(color)}`. Be careful with that, it will only work in the environment, which support Shadow DOM natively. You can read more about it in https://github.com/hybridsjs/hybrids#limitations and possible solution here https://github.com/hybridsjs/hybrids/issues/10.

For simple components, I recommend inline styles in one file, and when you need some switches, use classes for that (and have one static stylesheet).

**Comment by akoushke** [comment]
thanks for the reply @smalluban. keep up the good work.

**Comment by smalluban** [comment]
Answer in https://github.com/hybridsjs/hybrids/issues/62
