### ISSUE TITLE
Undefined elements at runtime and dynamic inclusion

### ISSUE THREAD

**Issue by dobexx** [hybridsjs/hybrids#153]
Hello,

we are still very excited about your project. Excellent work. We now have tens of thousands of apps running with large parts of hybrids.

Now we want to switch from version 4.1.x to 5.2 and have noticed that under "render" the definition of element is checked via customElements.get. Since we include many components dynamically due to the runtime behaviour, a problem arises here. According to the Web Components standard, elements can be defined later and even be treated as "unresolved" via CSS.

If we exclude the check in the source code for hybrids, the version change goes through without a problem.

What is the background of this check? 
Is it possible to introduce a setting flag for an optional check?

Here is the source code line concerned:

https://github.com/hybridsjs/hybrids/blob/636872a04a14a5418b8c7f5b130b788542106156/src/template/core.js#L343

**Comment by smalluban** [comment]
Hi! It's super cool that hybrids works for you so well! 

The only reason for the check is to prevent typos in the elements names. I know now that some IDE's have support for checking html`` template literals, but still if you misspell element can have a weird bug.

However, I understand your point of view about the standards. Elements can indeed be defined later or even not defined on purpose. As I removed modes from the code (dev/prod), I`ll remove the check and release new version with a fix.

**Comment by dobexx** [comment]
Thank you for the prompt reply and change, as always.

Regarding the runtime costs of customElements.get, I could imagine that an unnecessary brake is removed here.

**Comment by smalluban** [comment]
Fixed in `v5.2.1`.

**Comment by dobexx** [comment]
Thank you for the update. After the update, placeholders "{{}}" like the ones you see are now displayed. 

After reverting to 5.2.0 or 4.2.x it works again. Maybe something more was changed here?

![Screenshot 2021-04-09 15 43 07](https://user-images.githubusercontent.com/5087406/114189830-e8f60900-994a-11eb-9069-58b377c39c91.png)

**Comment by smalluban** [comment]
Yes, I did some clean up, as all of the tests pass. Can you provide the part of template which produces an error?

**Comment by smalluban** [comment]
I'll revert the clean up or find another solution, but I would like to create a test case to protect from introducing big in the future.

**Comment by dobexx** [comment]
Here is a screenshot with an excerpt of the template. If required, I will be happy to supply the entire web component.

![Screenshot 2021-04-09 17 32 32](https://user-images.githubusercontent.com/5087406/114204563-9ec85400-9959-11eb-93e0-3eb02290f563.png)

**Comment by smalluban** [comment]
Thanks for a fast reply. I have to say, that I was trying to be smarter than myself, and I thought that one place during compilation can be written cleaner. However, it was written in that way on purpose ;)

For now, the test is updated, so it fails with the `5.2.1`, but it is fixed in `5.2.2`. Please, try the newest version, and let me know if anything else is still not working properly.

**Comment by dobexx** [comment]
Sometimes people overshoot the target. 

Perfect. Now it's running again. Thank you very much. 

Now we can take a closer look at the new store function and factory.

**Comment by smalluban** [comment]
Ok, so I'm closing the issue. Feel free to comment and re-open if necessary.
