### ISSUE TITLE
Declarative Shadow DOM

### ISSUE THREAD

**Issue by oncode** [hybridsjs/hybrids#154]
First thanks for the awesome library! It makes writing WebComponents really fun. 🤩

With the introduction of Declarative Shadow DOM in Chrome 90 (https://web.dev/declarative-shadow-dom/#hydration), it's now possible for a Custom Element to have a shadow root before it gets upgraded. Maybe it would be nice to have a `renderSSR/renderDeclarative` method in hybrids that is able to output the declarative markup for optimal hydration and remove FOUC:

```html
<custom-button disabled>
  <template shadowroot="open">
    <style>
      button {
        color: red;
      }
    </style>
    <button disabled>
        <slot name="icon"></slot>
        <slot></slot>
    </button>
  </template>
  <span slot="icon">👨🏼‍💻</span>
  Label
</custom-button>
```

What do you think?

**Comment by smalluban** [comment]
Hi @oncode! I've been watching the declarative shadow dom feature for a while. Sounds great that finally, it will be shipped in Chrome. I plan to support SSR, but the subject is much bigger than just re-using DOM from the server. For example, the template engine would replace html, as it must recognize content as it's template instance. But there is more, like nested templates, and now importantly a state of the component, which have to be serialized, including global store objects.

Still, I think That it is doable. However, for now, I want to finish router first, which also will be a part of SSR. It's almost done, so I should start working on that soon :)

**Comment by oncode** [comment]
Thanks for your quick feedback! Ah it looked more straightforward, but good to know that it's on the roadmap. :)
