### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by cfv1984** [hybridsjs/hybrids#155]
What's the browser support matrix for hybrids? I'd like to communicate this on any web components I end up building

**Comment by smalluban** [comment]
Hi! You can find it here: https://hybrids.js.org/#/getting-started/installation?id=browser-support. Generally, every modern browser, and of course without IE11. Support for that obsolete browser was removed in `5.0.0`.

**Comment by iyunusov** [comment]
You tiny little prick, who do you think you are ? Once I catch you alone, I will teach you how to mind your own business. Arsehole nerd!
