### ISSUE TITLE
Possible extension for html.set in terms of polymer data binding (propertyname-changed event)

### ISSUE THREAD

**Issue by dobexx** [hybridsjs/hybrids#160]
Hello,

we are currently transitioning many of our web components to hybrids. Since we use many UI elements from Polymer, there is always an event called "propertyname-changed" when properties are changed. In this event, the value is passed on under detail.value.

It would be great if the integrated helper function html.set() under the method resolveValue() simply checks whether there is detail.value and then uses this instead of the target.value.  

This is to be seen e.g. well with the element paper-toggle-button, with which property "checked" is then simply transferred over it.

**Comment by smalluban** [comment]
You can test it out using linked PR, just install hybrids with `npm i hybridsjs/hybrids\#fix-html-set-detail-support`

**Comment by dobexx** [comment]
Just tested successfully. As always perfect and incredibly fast implementation.👌👌

**Comment by dobexx** [comment]
Attention! This export does not exist in value.js in this branch!

`import resolveTemplateValue from "./resolvers/value.js";`

**Comment by smalluban** [comment]
It's a default export, renamed, as there is a function with the same name, so no worries :) everything works fine.
