### ISSUE TITLE
Understanding problem with store and set connect method

### ISSUE THREAD

**Issue by dobexx** [hybridsjs/hybrids#161]
Hello,

currently we are making very good progress with the integration of your store feature. However, the connect set method is giving us some headaches. Maybe we are a bit lost in understanding this. 

The API call does not return the full instance of the backend. This is explicitly intended in this case. The passing parameters from the set connect method does not do it either. How can we solve this problem or approach it differently?

```js
export const MainIntroContent = {
	id: true,
	full_content: '',
	[store.connect] : { 
		get: url => {
			if (!url || !url.length) return {};
			return fetch(url, {
				credentials: 'include',
			})
			.then(r => r.json());
		},
		set: (url, values) => {
			return fetch(url, {
				method: 'PUT',
				headers: { 'Content-type': 'application/json;charset=utf-8' },
				credentials: 'include',
				body: JSON.stringify(values)
			})
			.then(r => r.json())
			.then(data => {
				// Question: How can the original store instance be returned here?
				return { ...data, id: url };
			});
		}
	}
};
```

**Comment by smalluban** [comment]
Let me know if I understand correctly. You have a model, which when set requires some properties, but when get it doesn't? 

The store models must have defined all of the properties. Your set method will get only those properties (in `values`), which are defined in the definition. The client model does not have to reflect your API models strictly. You can also as the result of set method return model, which does not contain those properties, so the values will be empty (default).

```js
const Model = {
  id: true,
  full_content: "",

  // set parameters
  param1: "",
  param2: "",
  
  [store.connect]: {
    get: () => ...,
    set: (url, values) => fetch(url, { ..., body: JSON.stringify(values) })...
  },
};
```

If your PUT method will return only `{ full_content: "..." }`, your parameters will be cleared, and will be empty, so they are actually never saved.

**Comment by dobexx** [comment]
I missed the explanation. Now a light has dawned on me. The same principle as with the property setter. Sometimes you can't see the forest for the trees. 

Ok, we just commit the change to the backend and then return the original instance with the changes already incorporated.

Great solution. Thanks for this help.

Here is the modified code snippet:

```
export const MainIntroContent = {
	id: true,
	full_content: '',
	[store.connect] : { 
		get: url => {
			if (!url || !url.length) return {};
			return fetch(url, {
				credentials: 'include',
			})
			.then(r => r.json());
		},

		set: (url, values, keys) => {
			
			let changes = keys.reduce((changes, key) => { changes[key] = values[key]; return changes; }, {});
			
			return fetch(url, {
				method: 'PUT',
				headers: { 'Content-type': 'application/json;charset=utf-8' },
				credentials: 'include',
				body: JSON.stringify(changes)
			})
			.then(() => values);
		}
	}
};
```

**Comment by smalluban** [comment]
Happy that I could help :)
