### ISSUE TITLE
a meteor compiler?

### ISSUE THREAD

**Issue by crapthings** [hybridsjs/hybrids#163]
how to make this work with meteor.js?

**Comment by smalluban** [comment]
Never tried meteor.js in practice (I know the project, but only from the docs). For now, hybrids works only on the client-side, so I suppose that you should generate your view in meteor as usual (and treat web components like other built-in elements, like `<p>` or `<h1>`). They will be upgraded on the client-side, if you include your code with definitions and `define()` function.

**Comment by smalluban** [comment]
Feel free to re-open, if there is anything else we can talk about the meteor.js integration.
