### ISSUE TITLE
import as node module (import {...} from 'hybrids') doesn't work

### ISSUE THREAD

**Issue by AngeloKreienbuehl** [hybridsjs/hybrids#178]
**steps to reproduce:**
`$ npm init -y`
`$ npm i hybrids`
_create a component_
```js
import { define, html } from 'hybrids'

define({
    tag: 'hello-world',
    render: () => html`<h1>Hello world...</h1>`
})
```
_create index.html and add the component (script & tag)_
```html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="./hello-world.js" type="module"></script>

        <title>Hybrids</title>
    </head>

    <body>
        <hello-world></hello-world>
    </body>

</html>
```

Doing this gives me the following error:
safari (TypeError: Module specifier, 'hybrids' does not start with "/", "./", or "../". Referenced from http://127.0.0.1:3000/hello-world.js)
chrome (Uncaught TypeError: Failed to resolve module specifier "hybrids". Relative references must start with either "/", "./", or "../".)

**Comment by smalluban** [comment]
Hi @AngeloKreienbuehl! Bare imports (those without absolute path, like `import ... from "hybrids") are not supported natively in the browsers, by default. You have two options:
1. Use CDN, and import from the URL, like this: `'https://unpkg.com/hybrids@^6'`
2. Use bundles, like Vite, Snowpack or parcel, which translated and bundle bare imports

You can read more here: https://hybrids.js.org/#/getting-started/installation

**Comment by AngeloKreienbuehl** [comment]
Wow. Thanks for the fast response!
Do you know if there's a way to use the cdn-option in typescript?

**Comment by smalluban** [comment]
I think it might be possible to map your URL import with local copy of hybrids library, so then typings will be matching, but I've never try to do something like this.
