### ISSUE TITLE
Update to documentation

### ISSUE THREAD

**Issue by rschooley** [hybridsjs/hybrids#180]
I don't see a separate project in GH for the documentation, or a way to suggest a change directly on the site, so please let me know if you'd like this filed another place.

on https://hybrids.js.org/#/misc/typescript

1. I think `define` needs a `tag`, either as the first arg or on the object body
2. The `descriptors structure` and `translation` links lead to 404s

**Comment by smalluban** [comment]
I am preparing a big update with `v7`, however, I had to forget about updating this section with tagged components. Thanks! I will fix that soon. The docs are in this repository in `/docs` path, so the file you found issues is here: https://github.com/hybridsjs/hybrids/blob/master/docs/misc/typescript.md

I am busy recently (moving to new house), so it can take some time to release new version, but I will try to fix the docs :)

**Comment by smalluban** [comment]
I'm closing the issue as I've released the `v7` with rewritten documentation. If you find any issues, feel welcome to open another issue.
