### ISSUE TITLE
Custom methods on component ?

### ISSUE THREAD

**Issue by fsicre** [hybridsjs/hybrids#183]
Hi Hybrids,

with this snippet
```html
<script type="module">
  import { define, html, } from 'https://unpkg.com/hybrids'

  define({
    tag: 'my-tag',
    name: 'World',
    met: function(host, v) {
      host.name = v
    },
    render: ({ name }) => html`
      <div>Hello ${name}!</div>`
  })

</script>
<my-tag id="test" name="Marco"></my-tag>
```

if I do in JS console
```
test.met('Hybrids')
```
the
Hello World!

change to 
Hello undefined!

can't we have methods on components ?

**Comment by smalluban** [comment]
Hi @fsicre! 

If the property is defined as a function, it is called when you access the property (like a getter in the computer properties). You can read more about it in the [Structure](https://hybrids.js.org/#/component-model/structure) section of the docs.

However, the computed property can return whatever you want, so you can make the property be a function for the user easily:

```js
define({
  ..., 
  met: function(host) {
    return function(name) {
       ...;
    }
  }, 
});
```

As you can see above, you just need to return a function in the property definition. Technically, return a function inside the wrapper function. If in the main function you don't use other properties, the result function is cached, and the property returns always the same generated function.

For simplicity, I recommend using arrow functions, so it then looks simpler:

```js
met: (host) => (name) =>...
```

**Comment by fsicre** [comment]
Awesome!
You're right, this snippet has no sense, It was just here to show you my problem.
Thanks a lot @smalluban.
