### ISSUE TITLE
Tailwind integration

### ISSUE THREAD

**Issue by fsicre** [hybridsjs/hybrids#184]
Hi,

I'm aiming to build a library of WebComponents styled with Tailwind.

Do you have any recommandation on how to achieve this integration with Hybrids ?

**Comment by smalluban** [comment]
I'm not a Tailwind user, but the comment from another issue might be helpful for you: https://github.com/hybridsjs/hybrids/issues/120#issuecomment-654637582

In short, if you can produce text content of the CSS from another file (which can be processed by the Tailwind), you can easily apply those styles by `.style()` helper of the template engine.

**Comment by fsicre** [comment]
The technique describe in this comment works well.
Thanks a lot. Huge time saving.
