### ISSUE TITLE
Update Store based on previous value

### ISSUE THREAD

**Issue by rubixibuc** [hybridsjs/hybrids#185]
Hi!

Regarding updates to a Store in quick succession, how do we safely update the value based on the previous state?

I'm noticing that the value retrieved from the Store factory is not the immediately previous value since the setter is async. I wasn't able to find this in the docs, I might be missing it though.

Thank you!

**Comment by smalluban** [comment]
Hi @rubixibuc! Can you provide a simplified example of what you want to achieve? I'm not sure what value you mean, some outside of the store model? 

If you mean something with displaying data, there are gouards, which checks the current state of the model. If you update already fetched model, you should use combination of ready and pending guards:

```js
store.ready(model) && !store.pending(model)
```

This is intentional behavior, as the store updates the model asynchronously, while still returning the last cached value. It's powerfully feature, as you don't have to worry about empty state of data when updated.

**Comment by rubixibuc** [comment]
No problem!

So based on what I'm seeing both of these calls see the original value of the store instead of the one from the previous update.

```javascript
import { store } from "hybrids";

const Settings = {
  count: 0,
};

store.set(Settings, { count: store.get(Settings).count + 1 });
store.set(Settings, { count: store.get(Settings).count + 1 });

setTimeout(() => console.log(store.get(Settings).count), 2000);
```

This outputs "1". I understand the sets are async, but is there a way to call them in sequence based on the previous value from other calls?

My use case involves the store factory and multiple components that update the store, but this example exemplifies the question cleaner.

**Comment by rubixibuc** [comment]
Got it, ty!

Follow up question though, 

here is my component 

```javascript
{
    settings: Store(Settings)
}
```

is `host.model` in this case `host.settings`? and could it be a derived property as well?

like

```javascript
{
    settings: Store(Settings)
    count: ({ settings }) => settings.count
}
```

where `host.model` could be `host.count`

Sorry I'm trying to grasp what `host.model` is in `store.resolve(host.model)` is according to the api,

**Comment by smalluban** [comment]
I had to look into the source to be sure ;) The store protects from setting a model twice at the same time. It checks if the model is pending, and schedules the next update. However, you can't avoid resolving the model, where your line with `await store.set()` will get the same model instance, so the value will be overwritten with the same old value. It's technically impossible. The store still works, but you should not rely on the previous value. 

Generally, the store wasn't designed to support that case. The models can store data, but they should be as stateless as possible, so the current value should not be related to the previous one.

I'm not seeing a bigger picture of your problem, but what would suggest is updating the `unhealthyCount` in one place, for example in some root level element. You can use `children()` factory to get statuses of those elements, and wherever they change, you can update the state value:

```js
import { define, children, store } from "hybrids";

define({
  tag: "some-parent",
  components: children(MyChild),
  unhealthy: {
    get: ({ components }) => components.reduce((acc, { healthy }) => acc - Number(healthy), components.length),
    observe(host, value) {
      store.set(ProjectsState, { unhealthyCount: value });
    },
  },
  ...
);
```

**Comment by rubixibuc** [comment]
I understand.

The children in my case are in the shadow dom not in the light dom.

So my components would look something like

```javascript
childComponents: children(ChildComponent),
someArray: void 0,
render: () => html`${someArray.map((child) => html`<child-component child="${child}"></child-component>`)}`
```

in this case `childComponents` always seems to return 0.

sorry for all the issues.

Is there a way I can solve it using this pattern? I'm not sure using slots makes sense in this case since the parent excepts an array of children. I think I would have to create a third component to wrap both in the other case.

**Comment by smalluban** [comment]
The children factory indeed only scans the light DOM (it is also a technical limitation to the MutationObserver API). In this case, you can use `content` property (to render in light DOM; if you don't use styling and slots, it is recommended), or use `parent()` factory (which go through the shadow DOM boundary). In this case, your parent should have some `count` property, chich children when mounted (and fetched those data) update the value if they are healthy. The property set is synchronous, so the value is always up to date:

```js
const Parent = define({
  tag: "my-parent",
  healthy: 0,
  render: () => html`...`.
});

define({
  tag: "my-children",
  ...,
  parent: parent(Parent),
  healthy: {
    get: ({ status }) => status === 200.
    observe({ parent }, healthy) {
      parent.healthy += healthy ? 1 : - 1;
   },
});
```

**Comment by smalluban** [comment]
After a while, I found a similar, but a more clear solution, using DOM events, so the parent and children don't have to know implementation details of each other. 

* In your child element, in `observe()` method dispatch custom event with the healthy status (remember about `bubbles: true`). 
* In your parent element render method, where you put your components, listen to this event by `<my-children onstatuschange=${doSomething}></my-children>`. 

It can still be a value in the parent, which is synchronously updated.

**Comment by rubixibuc** [comment]
I think this is how I will do it.

Thank you for working through it!

I understand the store use case better now as well :)

**Comment by smalluban** [comment]
Cool, let me know if it worked out, and of course re-open the issue if you have any question about the subject.
