### ISSUE TITLE
How to compile statically?

### ISSUE THREAD

**Issue by MohammadMD1383** [hybridsjs/hybrids#186]
I mean, my server is not nodejs server, so I want to have the compiled js files of web components, how should I do that?
thanks.

> for example tailwindcss will generate a css file
> can hybrid also generate js files?

**Comment by smalluban** [comment]
Do you mean bundled web components? Hybrids is just a library/framework. You can choose any bundler to create a production build if you wish. I can recommend https://vitejs.dev/ for sure, it works out of the box without special configuration.

**Comment by MohammadMD1383** [comment]
so my opinion is to minify the files myself and serve them as es modules. is that rational?

**Comment by smalluban** [comment]
It depends on your needs. Do you plan to provide web components separately for the users, or you are using them internally, for example for another project?

**Comment by MohammadMD1383** [comment]
I want to use them in my website, which is hosted by **java**

**Comment by smalluban** [comment]
I would want to help here, but I think your problem is out of the scope of the library itself. It is rather the project setup problem. It will be hard to say something without knowing the details of your project. Also, I am not familiar with Java web technology.
