### ISSUE TITLE
Typing Issue When Redefining HTMLElement Built-In Properties

### ISSUE THREAD

**Issue by auzmartist** [hybridsjs/hybrids#187]
Hello again @smalluban!
Thanks again for a great 7.0 release. It's been largely really stable as I've upgraded quite a few projects. 👍 

Something I've noticed related to Typescript - the type for Component<E> does not seem to allow redefinition of HTMLElement properties. This poses a typing problem for components which would like to redefine a built-in property `title` or `lang` for example.

Minimal Reproduction:
https://stackblitz.com/edit/typescript-h6sc4x?file=index.ts

You mention this briefly in your Built-Ins section here:
https://hybrids.js.org/#/component-model/typescript?id=built-ins

Functionally, this pattern works well and can be desirable for achieving an ideomatic component interface. On the other hand, I would understand your hesitancy to allow overriding certain properties.

WDYT?

**Comment by smalluban** [comment]
Hi @auzmartist!

> It's been largely really stable as I've upgraded quite a few projects. 👍

Great!

About the problem, it is a TS limitation, or I don't know some hidden feature. The `Component` type takes a generic type, and it must iterate over the props to map the interface values to the hybrids properties definitions according to the API. Unfortunately, if you extend the interface, there is no way to know, which props are from the definition itself or from the base (by the `extends`). In the end, if you create an interface with `HTMLElement` base, without extracting, there is another problem - TS complains that values in the passed object to the `define()` function do not meet the required type.

**Comment by smalluban** [comment]
@auzmartist Feel free to re-open, if you need some more help here.
