### ISSUE TITLE
AsyncIterator

### ISSUE THREAD

**Issue by fsicre** [hybridsjs/hybrids#189]
Hi,

is there any best practice using an AsyncIterator with an Hybrid component ?
(without store, if possible)

Thanks

**Comment by smalluban** [comment]
Hi @fsicre. Async iterator must be run in the async function, which returns a promise, so what you need to do, is just use `html.resolve` helper in the template (if you want to display something that this promise returns):

```javascript
define({
  tag: "my-element",
  asyncData: async () => {
    const result = [];
    for await (const val of ...) {
      result.push(val);
    }
    return result;
  },
  render: ({ asyncData }) => html`
    <div>
      ${html.resolve(
        asyncData.then(list => list.map(val => html`...${val}...`)),
      )}
    </div>
  `,
};
```

**Comment by smalluban** [comment]
Fell free to re-open if you need more guidance.
