### ISSUE TITLE
property factory: Immutability and Object.freeze 

### ISSUE THREAD

**Issue by robertpage** [hybridsjs/hybrids#19]
I'm still feeling hybrids out so I may have missed something really obvious and I apologize in advance if that is the case. Default freezing of objects seems limiting to me. Maybe this is intended as an opinionated part of hybrids or is inherently built in for reasons I don't understand yet. Honestly, I'd rather that preventing mutations was left up to me and I could freeze objects when I declared them instead of it being a default. Looking at the Todo example seems like it's jumping through a lot of hoops to update array values. Anyways, super excited about this framework! It's been great poking at it for a small test project. Thanks!

**Comment by smalluban** [comment]
`Object.freeze` s there only to protect you from making a mistake. The whole idea behind cache mechanism is to compare equality between changes, so all object values should be immutable. Internal changes to object properties will not cause re-render or refresh other related properties.

However, I looked at the todo example, and I refactored it slightly. If we have all control over implementation, using freezing might be overkill, so I removed it from `parseJSON` transform function. Also, a pattern to add methods to custom elements is something that I consider wrong lately. Please, look at that example again. It should be clearer and easier to understand now.

Also, thanks to you I started to re-think my decision behind using `Object.freeze` for object values in property factory. I still think it should be used for default value - it is shared between all instances (which is some kind of anty-pattern in classes). To be 100% sure, that code does not break immutability here, the freeze is the only option. However, it might be not necessarily needed when the value is overwritten in the scope of one instance.

**Comment by robertpage** [comment]
Thanks for responding with such a thoughtful answer! Everything you said make sense. I think for me it was about the size and complexity of the project I was working on that brought up my questions. Object values being immutable makes sense, and honestly, I think being the default is the right decision. I guess the question is, how much rope can you give someone before it's enough for them to inadvertently hang themselves. I like the idea of having access to an object that can be mutated and doesn't cause a re-render and another default object that I can trust and does cause re-renders. Then I can decide how and when I use them. That said, if I was working on a larger project with a number of other developers I might change my mind on that quickly :sweat_smile:. Thanks again for such an awesome library!

**Comment by smalluban** [comment]
Feel free to re-open if something comes to your mind.

**Comment by coedder** [comment]
I'm trying to understand. The real reason behind `Object.freeze` is this: 

> Internal changes to object properties will not cause re-render or refresh other related properties.

Then `Object.freeze` is prevening us try to change nested object properties? Then if we detect the internal changes there will be no need of  `Object.freeze`. Right?  Or there is another reason too?

**Comment by smalluban** [comment]
It's only there to prevent you from making mistake and mutate object nested properties of property factory value. You may think that mutation should cause an invalidation, but it won't. The library uses only equality check for change detection.

As I wrote earlier, I'm not sure if we really need `Object.freeze()` in object transform, but you may create own transform function and omit freezing objects. It is one of the default behaviors when you pass an object as a default value. 

Insted of writing something like this:

```javascript
const MyElement = {
  value: property({ one: 'two' }),
};
```

You can write:

```javascript
const MyElement = {
  value: property((input = { one: 'two' }) => input),
};
```
The above example does not provide type check, so you can pass anything - it only shows, that you are not tied to one solution provided by the default behavior of the library.
