### ISSUE TITLE
Initializing object properties with `undefined` no longer accepted in v8.0.0

### ISSUE THREAD

**Issue by Hyzual** [hybridsjs/hybrids#190]
Hello, first of all thanks for the continued maintenance of this great library ! 😊

I was about to update to v8.0.0 but stumbled upon [a change in the TypeScript definitions][0]. Following the [documentation on Descriptors][1], `undefined` has special meaning for property descriptors: it creates a writable property with default value. We sometimes use Object properties (that cannot be set via attributes) in our elements, so when there was no reasonable default value, we would use `undefined` to initialize them. The caller (in our case another element) had to make sure to set the property, but otherwise it never caused any problem. We knew the property must be set to use the element and that it wouldn't work without it.

On v8.0.0  it is no longer possible to do that, as it raises a TypeScript error:
> Type 'undefined' is not assignable to type 'Property<ComponentWithObjectProperty, ObjectProperty>'.

I have set up a reproduction here: https://codesandbox.io/s/hybrids-object-property-descriptor-with-undefined-si5vru
In the HTML rendering, you should see `#123 My object`. If you change the `hybrids` version to `7.1.0` in the `package.json` file, the TypeScript error should no longer be raised.

I have several questions regarding this change:
1. Is it intentional to disallow initializing object properties to `undefined` ?
2. Does this change mean we always have to set a default value to object properties ? That would be a bit annoying, especially with complicated object types.

Have a nice day !

[0]: https://github.com/hybridsjs/hybrids/blob/510de1f4ced7742ae37ca3127ff6c007441a4474/types/index.d.ts#L3
[1]: https://hybrids.js.org/#/component-model/structure?id=primitives

**Comment by smalluban** [comment]
Hi @Hyzual. It might be a bug in the typings, but I need more time to investigate. I will be back soon with answers.

**Comment by smalluban** [comment]
After a while, I discovered, that in the local example project, where I am testing the TS types, I did not set up the server, so the `"strict"` field was turned off by default. You're right, and it is a bug. I've released the patch (`v8.0.2`), so it should be ok now. 

Thanks for rising the problem.

**Comment by Hyzual** [comment]
Thanks for your quick answers and the fix ! I'll try it out shortly 😊

**Comment by Hyzual** [comment]
It works well, upgrade is done. :tada:
