### ISSUE TITLE
connect: addEventListener on components

### ISSUE THREAD

**Issue by DavideCarvalho** [hybridsjs/hybrids#20]
I wanted to know if there is a way of adding a eventListener to the component that listen do "document". I've tried doing something that looked like redux connect function but I wasn't able to make it work.
Could you provide some example? Or at least put it on the docs,

**Comment by DavideCarvalho** [comment]
It worked! TY for the help.
I also created a codesandbox to share. If you want, you can use it as an example
https://codesandbox.io/embed/r5nkxjo4ln

**Comment by smalluban** [comment]
You can use `dispatchEvent` from the library to simplier syntax:

```javascript
import { dispatchEvent } from 'hybrids';

dispatchEvent(document, 'event-name', { detail: { value: 0 } });
```

It creates CustomEvent for you and passes options.

**Comment by DavideCarvalho** [comment]
It gave me an error ```(0 , _hybrids.dispatchEvent) is not a function```
I commented the line so it's easier if you want to test

**Comment by DavideCarvalho** [comment]
The name isn't dispatchEvent, but dispatch

**Comment by smalluban** [comment]
Yes, you are right. I was writing it on my phone, fixed comment with the proper name.
