### ISSUE TITLE
`class` attribute changes rendering in v8.1.7

### ISSUE THREAD

**Issue by Hyzual** [hybridsjs/hybrids#201]
Hello,

I was about to update to v8.1.7 but when testing I've found an issue in the HTML rendering. It seems the `class` attribute changes the HTML output when it is present.

I have set up a reproduction here: https://codesandbox.io/s/hybrids-class-attribute-changes-rendering-nzjkh3
In `src/index.ts`, if you remove the `class` attribute on the `<tbody>`, the `<tr>` elements should be children of `<tbody>` (as expected). With the `class` attribute present, they are instead children of the custom element itself (siblings of `<table>`).

v8.0.10 is not affected, if you need a starting point for `git bisect`.

Let me know if I can help further. Have a nice day !

**Comment by smalluban** [comment]
Thanks for rising this up! I will try to check it out as soon as possible.

**Comment by smalluban** [comment]
I've introduced a bug when refactoring the template engine compilation process. The above commit should fix the issue. When tests pass on main branch, I will release a new patch.

**Comment by Hyzual** [comment]
I've just tried pulling the commit above, it fixes all the issues I've run into. Thanks a lot for the insanely fast bug fix 🙇💪

**Comment by smalluban** [comment]
The `v8.1.8` has been released. Please, re-open the issue, if the problem still exists.
