### ISSUE TITLE
React integration - Error while unmounting the component

### ISSUE THREAD

**Issue by dinoiam** [hybridsjs/hybrids#211]
Hello everyone, inside our platform we have this hybrids component that is behaving strangely.
Everything seems fine during the render face but when I switch page and then (I guess) react is trying to unmount the component I got this error. 

**Component**
hybrids 4.3.0
hybrids-router  2.0.0

**React platform**
React 18.2.0
Node v18.17.0

**Dunno if you could help, but I'm out of ideas.** Thank you anyway for your time in advise!

<img width="1002" alt="Screenshot 2023-08-03 alle 09 04 05" src="https://github.com/hybridsjs/hybrids/assets/54214779/4417bac5-5f34-4585-a15d-d48bf7f533b5">

**Comment by smalluban** [comment]
Hi @dinoiam. You are using a pretty old version of hybrids and another package (hybrids-router), which is created and maintained by someone else.

However, I doubted that hybrids were freezing the whole element instance, so it is not possible to delete the property. You can check out if hybrids are indeed a problem by not calling the `define()` function for that component. The element should be still there, but the library won't define it.
