### ISSUE TITLE
about destructured host parameter in render function

### ISSUE THREAD

**Issue by woyodb** [hybridsjs/hybrids#213]
Hi there, I have a question that needs your clarification.  When I try to using destructured parameters on 'render' property function, I've got nothing from '...rest' part (call JSON.stringify(rest) and output is {}). Is this feature supported? 

```js
{
	propA: 'A',
	propB: 'B',
	render: ({propA, ...rest}) => html`
		${propA} is shown.
		${rest.propB} is missing.
	`,
}
```

quick link to the showcase is here: https://codesandbox.io/s/cranky-engelbart-hckyx7?file=/src/index.mjs

Thanks...

**Comment by smalluban** [comment]
Yes, it won't work. As you can see the `rest` is empty even though it's an HTMLElement instance with a lot of properties... so how does it work? 

By the design all of the elements properties are defined on the prototype as getters/setters (not directly on the element). The library follows that behavior here: https://github.com/hybridsjs/hybrids/blob/5716c5545151e3637220387a290db4fa18dee7a3/src/define.js#L104

If it would work differently it could break some code, as your custom element can be scanned in some way, and it should behave just like ordinary elements.

**Comment by woyodb** [comment]
Thanks for your detailed clarification. It's obviously very clear. I really appreciate it.
