### ISSUE TITLE
A storage without an identifier loads data even before assigning an identifier

### ISSUE THREAD

**Issue by Qsppl** [hybridsjs/hybrids#216]
I created a [storage without an ID](https://hybrids.js.org/#/store/usage?id=without-identifier) to load the model after clicking the button.

When a store is created, it immediately tries to load data, even though the store has not yet been given an ID.
As a result, the storage uses the value undefined as the ID and goes into the ready/error status.
This breaks the work of the [Defenders](https://hybrids.js.org/#/store/usage?id=guards).

storage testing example:
https://codepen.io/qsppl/pen/MWZddwE?editors=1010

an example of Defenders not working properly:
![image](https://github.com/hybridsjs/hybrids/assets/22717464/0a80da0f-f3d9-4bac-8194-f65fab2e2278)

**Comment by Qsppl** [comment]
Working solution. Load component when clicked:
https://codepen.io/qsppl/pen/YzdboRr?editors=1010

**Comment by smalluban** [comment]
Your `relatedContacts` is a listing model. The store must load it, as it cannot assume that without id it should not return results. It is even more often that listing models returns a list of models without taking arguments. 
I already provided solution here https://github.com/hybridsjs/hybrids/issues/214#issuecomment-1764310412

If there is something else regarding the subject, feel free to re-open.
