### ISSUE TITLE
Starter / template repository ?

### ISSUE THREAD

**Issue by mykulyak** [hybridsjs/hybrids#217]
Hello,

I'd like to use Hybrids for my next project. The project is a big SPA app (an IDE), which I want to create using Hybrids only.

Is there any example projects which I can use as starting point ?
I already looked in the documentation and to the [hybrids template](https://github.com/hybridsjs/template).

**Comment by smalluban** [comment]
Currently, there is no template project from the hybrids itself. I have plans to do so, but there are other things on the list too ;)

I recommend looking at https://github.com/ghostery/ghostery-extension/tree/main/extension-manifest-v3/src/pages - here you have a simple setup for each "page" of the extension, which uses routing, store, auto import and other stuff.

**Comment by smalluban** [comment]
Feel free to re-open, if have any ideas on how to make a good starter project. When I get back to this subject, I'll let you know here.
