### ISSUE TITLE
An error occurs when saving a Draft

### ISSUE THREAD

**Issue by Qsppl** [hybridsjs/hybrids#220]
Example:

https://codepen.io/qsppl/pen/mdvKrWP?editors=1011

We create several forms with the model in “Draft” mode.
![image](https://github.com/hybridsjs/hybrids/assets/22717464/98437fa4-d771-4445-881a-5d88f1167ef6)

Let's try to save them.
![image](https://github.com/hybridsjs/hybrids/assets/22717464/cf9aa485-fcfd-4b03-985b-3a677bddd205)

We see a bug:
> Local and storage data must have the same id: '3c981b3b-f454-4402-a51f-92569fbe36ac', '7'

I tried to write a solution without linking Draft to "id", but it didn't work:

https://codepen.io/qsppl/pen/wvNEjBw?editors=1011

**Comment by Qsppl** [comment]
I tried to solve the problem through a single model descriptor that does not have an Id and is always in Draft mode. It didn't work out either. All components without a defined model receive the same model after the first model is created in one of the components:

https://codepen.io/qsppl/pen/NWoLMYR?editors=1011

**Comment by Qsppl** [comment]
This is the case from the editable table

![image](https://github.com/hybridsjs/hybrids/assets/22717464/8e49abac-5be4-49ab-8899-a807cf2fe130)

**Comment by smalluban** [comment]
I've started building an example, and I think I finally understand your case. If I am correct, you have some sort of rows, and you can add a comment to each, but it is a "create" form - and in your case, a user can open multiple forms at once.

Unfortunately, the current implementation of the draft model fails in that case, as I wrote earlier, you can't have multiple instances of the draft without passing id. 

I'll try to rethink what can be done for you. In the meantime, I hope that you have some workaround of the issue, and it does not block you.

**Comment by Qsppl** [comment]
I solved the problem. I'm showing only one on-demand creation form.

![image](https://github.com/hybridsjs/hybrids/assets/22717464/a8b65040-4531-4f05-854a-be8f6be16426)

![image](https://github.com/hybridsjs/hybrids/assets/22717464/254caa6f-796a-41f7-91b9-fb5d6b8092b6)

But it is very inconvenient to control the components so that only one form is open at a time.

I also had to create two components:
- `contact-comment-remind.component.ts`
- `contact-comment-remind-create.component.ts`

Instead of one:
- `contact-comment-remind.component.ts`

Duplicate html and css markup. This becomes a problem when there are more than 10 models in the table. Each model requires two identical components instead of one.

But this solution supports Store validation.

**Comment by smalluban** [comment]
Good to know that you have temporary solution. I'll try to rethink it as soon as possible, and back with more general way to handle that case.

**Comment by smalluban** [comment]
After all, I figure out, that store can create a local temporary id for the draft model, as it is very unlikly that it might hit an existing ID of the storage.

If it is possible, please test it out before merging and relese, using codesandbox build:

```
"dependencies": {
    "hybrids": "https://pkg.csb.dev/hybridsjs/hybrids/commit/e530588f/hybrids"
  },
```

You can use it directly in your code or using codesandbox (link in the PR mentioned above).
