### ISSUE TITLE
A draft model instance with an empty ID returns an error when editing

### ISSUE THREAD

**Issue by Qsppl** [hybridsjs/hybrids#223]
Example: https://codepen.io/qsppl/pen/WNPPdym?editors=1010

![image](https://github.com/hybridsjs/hybrids/assets/22717464/088e0ad4-4609-48ab-ab81-8ef5cfc472df)

If the ID is defined, an error occurs when editing the draft
![image](https://github.com/hybridsjs/hybrids/assets/22717464/e01fbbbb-2fc4-44df-9db8-9430700dbaad)

How to do it right? I tried using false instead of "" as the model id value - didn't work. Tried using -1 and returning an empty model, but that seems like a bad solution.

**Comment by smalluban** [comment]
It looks like you make not-covered edge cases ;) I made a fix, so just update to `v8.2.8` and your case should work.

However, when using the draft mode, I recommend to not use the `id` setting. When the `id` is omitted, the model property itself can be set with a model instance or just an id. In your case you share the form with the presentation, which I also recommend to split. So then you have clean model form, which takes a model id, or not if it is a "create" mode:

```js
{
 tag: 'a-comment-form',
 comment: store(Comment, { draft: true }),
 ...
};
```

Body of a comment component:
```html
   <div>${comment.body}</div>
   ${editMode && html`<a-comment-form comment="${comment}"></a-comment-form>`}
```

And create form in another place (without setting the comment):

```html
<p>Create comment</p>
<a-comment-form></a-comment-form>
```

**Comment by Qsppl** [comment]
Thank you. As for dividing the interface into presentation of models and forms for filling models with data, I wouldn’t want to do this. This reduces the accessibility of actions (in the case of separate edit pages or modal windows), or leads to duplication of markup and logic for "component" and "component-form" (in the case when for editing we replace the component with a form in the same place)

**Comment by Qsppl** [comment]
Example (changed*): https://codepen.io/qsppl/pen/WNPPdym?editors=1011

Clearing drafts no longer works.
It got id "2" and after that I can't set the component property to another draft.

![image](https://github.com/hybridsjs/hybrids/assets/22717464/3610a959-3a77-43fa-8c67-c659fa249461)

**Comment by Qsppl** [comment]
Thanks, I'll do it like this
