### ISSUE TITLE
Suggestion: Develop a solution that allows you to use a single component to create, edit and present a model

### ISSUE THREAD

**Issue by Qsppl** [hybridsjs/hybrids#225]
It just looks cool.

![image](https://github.com/hybridsjs/hybrids/assets/22717464/d2744192-6a9c-4a45-83ce-bfbadf7d0c1e)

![image](https://github.com/hybridsjs/hybrids/assets/22717464/7d6f0c5b-64cf-4767-9aeb-526b76154faf)

![image](https://github.com/hybridsjs/hybrids/assets/22717464/7271c4e0-89d6-481e-bc8b-79faf425e1a1)

![image](https://github.com/hybridsjs/hybrids/assets/22717464/1cc449f2-bb7e-45d2-b93f-2f71f67f463e)

Now, for such a result, you have to create two visually similar components `component` and `component-form`, replacing them if it is necessary to edit/create the model. These two components need to be maintained in a consistent state, logic, html and css markup must be duplicated. This makes development so difficult that it becomes easier to completely separate the view and the creation/editing form and place the form in a modal window. And since it’s simpler, that’s exactly how we have to work.

**Comment by Qsppl** [comment]
I can describe the problem in more detail and write an example. If this approach to development does not correspond to the Hybrids development style, then you can reject the proposal.

**Comment by smalluban** [comment]
I think you should be able to something similar to this:

```js
{
  model: store(Model),
  draft: store(Model, { draft: true, id: 'model' }),
  editMode: {
    get: (host, value) => !host.model || value,
    set: (host, value) => value,
  },
  render: ({ model, draft, editMode }) => html`
    ${editMode && store.ready(draft)
      ? html`<input ... vallue="${draft.content}" />...`
      : html`<div>${store.ready(model) && model.content}</div>`
    }
   ${store.ready(model) && html`<button onclick="${toggleEditMode}">edit</button>`}
  `,
}
```

**Comment by Qsppl** [comment]
Previously I tried a similar solution:

```JS
{
  modelId: "",
  model: store(Model, { id: 'modelId' }),
  draft: store(Model, { draft: true, id: 'modelId' }),
  editMode: {
    get: (host, value) => !host.model || value,
    set: (host, value) => value,
  },
  render: ({ model, draft, editMode }) => html`
    ${editMode && store.ready(draft)
      ? html`<input ... value="${draft.content}" />...`
      : html`<div>${store.ready(model) && model.content}</div>`
    }
   ${store.ready(model) && html`<button onclick="${toggleEditMode}">edit</button>`}
  `,
}
```

This didn't work: https://github.com/hybridsjs/hybrids/issues/223

Probably the mistake was that I used the `modelId` property as the id.

I'll test your solution in the near future.

**Comment by smalluban** [comment]
I made a working example on StackBlitz, here you have it - https://stackblitz.com/edit/hybrids-store-ui-form-example

Indeed, it didn't work - I think I found another case - where you pass the property name as `id` - it is taken as it is, not check if it is a model instance - so id is a stringified whole object. You must set id as a function (for now): 

```js
id: ({ model }) => model?.id
```

**Comment by Qsppl** [comment]
thanks, this works great.
