### ISSUE TITLE
how to create a component method

### ISSUE THREAD

**Issue by Qsppl** [hybridsjs/hybrids#227]
Due to the specificity of the "focusin"/"focusout" events, we must process only the last of the events generated in two consecutive macro tasks (including the macro task in which the first event was generated) from the moment the first event occurred.

This is easily solved by placing the event handler in a wrapper function.

native js example: https://codepen.io/qsppl/pen/poYvEVj?editors=1010
![image](https://github.com/hybridsjs/hybrids/assets/22717464/d13a3733-5105-4aa7-b63f-6887783bbbcb)

You cannot use a single deboucer for all components at once, since components can be nested within each other and then a single deboucer will not work correctly.
![image](https://github.com/hybridsjs/hybrids/assets/22717464/2d006ccb-635a-4289-8228-1e883e38ac1a)

This should be a method of the html element, but we can't assign that value to it.
![image](https://github.com/hybridsjs/hybrids/assets/22717464/0a7423ca-b082-4ec7-a542-8e645494bf3a)

**Comment by smalluban** [comment]
You can generate debounce instance in `connect` callback. If this is repeatetive pattern, the best way would be to create a factory for it:

```js
function debounceFactory(fn, options) {
  return {
    value: (_, value = fn) => value,
    connect(host, key) {
      host[key] = debounce(fn, options);
      return () => host[key].cancel();
    },
  };
}

const My component = {
  focusCallback: debounceFactory(...),
};
```

The above factory generates debounce for each instance of the component, and also protects from early access to the function before connecting to document.

**Comment by Qsppl** [comment]
I tried to create a descriptor directly, then I tried to use a factory to create a descriptor, but it all returns the same error as when using a function as a property value.
![image](https://github.com/hybridsjs/hybrids/assets/22717464/12a0ab16-bc53-47ab-9519-82d99544ddd3)

One of the previous examples returns the same error.
![image](https://github.com/hybridsjs/hybrids/assets/22717464/18784372-1d95-416a-ba88-c5653a68bbc5)

Even the types do not indicate that a function can be used as the value of the 'value' property.
![image](https://github.com/hybridsjs/hybrids/assets/22717464/59d012a4-10a2-4a16-bc9c-836e43f4bce6)

But it works if you declare the descriptor properties "get" and "set".
![image](https://github.com/hybridsjs/hybrids/assets/22717464/f45f3deb-7832-436d-adf7-fb99a8613b0b)

Did you make a typo in the example or did I break something?

P.S. I don't use descriptor factories because it's too difficult for them to specify types. Now it didn’t work out for me at all. Maybe create some kind of generic interface for factories?
![image](https://github.com/hybridsjs/hybrids/assets/22717464/bb195aad-332f-4680-acf0-871fe941e289)

**Comment by smalluban** [comment]
Sorry, I used upcoming syntax, sure it should be `get` / `set`, so it should look like this:

```js
function debounceFactory(fn, options) {
  return {
    set: (_, value = fn) => value,
    connect(host, key) {
      host[key] = debounce(fn, options);
      return () => host[key].cancel();
    },
  };
}
```

about TS, there is `Descriptor<T>` type, so it is straight forward to define factories in Typescript.

**Comment by Qsppl** [comment]
Thanks, it works
