### ISSUE TITLE
The "store(Model, { id: value })" descriptor does not resolve "id" correctly to the model instance.

### ISSUE THREAD

**Issue by Qsppl** [hybridsjs/hybrids#240]
https://github.com/hybridsjs/hybrids/blob/36df51a77b5baad2a179bb16fb8e1ff6010624af/src/store.js#L1518
```JS
const resolveId = options.id
    ? options.id
    : (host, value) => {
        if (value !== null && typeof value === "object") return value.id;
        return value ? String(value) : undefined;
      };
```

The `resolveId` function resolves `0` to `undefined`, but expects `0` to resolve to `"0"`.
This causes the error `TypeError: Provided model definition requires non-empty id: "undefined"`.
Example: https://codepen.io/qsppl/pen/rNbyOrm?editors=1010

**Comment by smalluban** [comment]
Thanks for  rising this up, fixed in https://github.com/hybridsjs/hybrids/commit/901b753986c4034b2244e7a59c365354579c85cb

Plase update to `v8.2.12`

**Comment by Qsppl** [comment]
Thank you

**Comment by Qsppl** [comment]
Solving this error resulted in another error that I can't find.

The component with model `{ id: 0, ... }` now receives a model, but then loses it:
https://codepen.io/qsppl/pen/jORBqed?editors=1010
