### ISSUE TITLE
The "store(Model, { id:value })" descriptor does not work correctly.

### ISSUE THREAD

**Issue by Qsppl** [hybridsjs/hybrids#241]
Solving this error resulted in another error that I can't find.

The component with model `{ id: 0, ... }` now receives a model, but then loses it:
https://codepen.io/qsppl/pen/jORBqed?editors=1010

_Originally posted by @Qsppl in https://github.com/hybridsjs/hybrids/issues/240#issuecomment-2009541659_

**Comment by smalluban** [comment]
The model `id` field is always a `string`. You cannot change that, but you can have a storage, which requires that. However, on the "hybrids" side - in the component, store model etc.. you should use string. For example, your model type is incorrect, as the `id` won't be a number. You should have this:

```ts
interface IModel {
    id: string // <--- it is always a string
    content: string
}
```

Still, I made a fix to protect from passing numbers (it only applies to this edge case when id is `0` - as this is falsy value in JavaScript).

https://github.com/hybridsjs/hybrids/commit/faec4c67cc255b60a705cd86c2ed8ef0f4703e3b
