### ISSUE TITLE
'"hybrids"' has no exported member named 'property'. Did you mean 'Property'?

### ISSUE THREAD

**Issue by JiaJasonLiu** [hybridsjs/hybrids#245]
I am using Typescript and started using the Hybrids framework recently.
I have been searching through the web and it seems that it I want to pass a prop to my component, I need the property function to state what type it is. 

![Screenshot 2024-03-22 at 16 26 12](https://github.com/hybridsjs/hybrids/assets/95042312/6c237a46-9202-4cb5-ae80-a5bf1a78e554)

Is there a workaround this because I can't seem to be able to use props with hybrids?

Thank you!

**Comment by JiaJasonLiu** [comment]
Furthermore, I am interpreting a template literal as an HTML template using `html``` in typescript.
Does this influence how data could be passed through?

**Comment by smalluban** [comment]
Hi @JiaJasonLiu! Welcome here. I strongly suggest to start with reading the official documentation. Each section has own Typescript page, with describes how to use it with TS. 

hybrids.js.org

Hybrids a long time ago had a `property` export, but no more :)

**Comment by smalluban** [comment]
Code example would be helpful, I am not sure what you mean.

Still, I encourage to read docs carefully - there is a section, which describes how to define simple properties: https://hybrids.js.org/#/component-model/structure?id=primitives

What you can learn there, is that properties defined as primitives protects the type, so if use set `count` to 'hello' it then is translated to a number: `Number("hello")`.

**Comment by JiaJasonLiu** [comment]
I figured out some of the other stuff thank you.

One question: I am defining an object as a prop to pass into hybridjs component called session


`sessionUser= {
id: string
lastLogin : number
`

passing that into my table
`
<user-table session=${tableData}>
</user-table>
`
```

interface Table {
  session: sessionUser[] | string;
}

async function gettingThings(host: any): Promise<string> {
  console.log('getting table', host.session)
  ...
}

export default define<Table>({
  tag: 'user-table',
  session: "undefined",
  user: {
      get: async host => await gettingThings(host),
    },
  render: ({ session}) =>
    html`<p>what is ${session}</p> `,

```

what I get in the logs are getting table [object Object] (which is just a string) 
and this
![Screenshot 2024-03-25 at 12 46 09](https://github.com/hybridsjs/hybrids/assets/95042312/2a5d1630-809b-48aa-9bdb-bcffb456c1d2)
So, I can't use it.

What are the whys that I can get objects as a prop?

**Comment by Qsppl** [comment]
Fine. Please ask in the future if other questions arise.
