### ISSUE TITLE
Add support for "TypeScript v5"

### ISSUE THREAD

**Issue by Qsppl** [hybridsjs/hybrids#247]
I found how to define separate types for different versions of TypeScript in the npm package:
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#version-selection-with-typesversions

You can now add separate type files for `TypeScript v4` and `TypeScript v5`

**Comment by smalluban** [comment]
I've found it too, but I think the current definitions should work in both (at least in v5).

**Comment by Qsppl** [comment]
Okay, I'll test it. If everything is ok, I will close the task
