### ISSUE TITLE
html|promise: Rendering property after http request

### ISSUE THREAD

**Issue by DavideCarvalho** [hybridsjs/hybrids#25]
I have a property that inside it's connect, I make a http request, but it sometimes render, and sometimes don't. I have to keep refreshing the page until one time the component renders the api response.

I'm doing like this:
```javascript
import { html } from 'hybrids';
import { getOngs } from '../services/ongsService';
import materializeStyle from '../styles';

const ongsProperty = ({
  get: (host, lastValue) => lastValue || [],
  set: (host, newValue) => newValue,
  connect: async (host, key, invalidate) => {
    host.ongs = await getOngs();
    return () => {};
  },
});

const ongsListRender = ({ ongs }) => html`
  ${materializeStyle}
  <h1>Help My.ONG</h1>
  ${JSON.stringify(ongs)}
  <ul class="collapsible">
  ${ongs.map(ong => html`
    <li>
      <div class="collapsible-header">${ong.name} - ${ong.taskTitle}</div>
      <div class="collapsible-body"><span>Lorem ipsum</span></div>
    </li>
  `)}
  </ul>
`;


const ongsList = {
  ongs: ongsProperty,
  render: ongsListRender,
};

export default ongsList;
```

I've made it work by putting a ```console.log(await getOngs())``` above ```host.ongs = await getOngs();```, but I guess this is a wrong thing to do.

**Comment by DavideCarvalho** [comment]
I tried to use ```invalidate``` method after the request, but still no success

**Comment by DavideCarvalho** [comment]
I removed the http request and put a mocked value, and it worked. Looks like promises doesn't work as it should

**Comment by smalluban** [comment]
Please, look at the [Promises](https://hybrids.js.org/template-engine/promises) section in the documentation.  There is an example, how to use async data in templates and more general in hybrids.

`connect` method is not a place to do calls. You should use getter to do that. Async request is only called again if cache invalidates (input related properties of your getter).

Your `ongs` property should be defined like this:

```javascript
const ongsList = {
  ongs: () => getOngs(),
  render: ({ ongs }) => html`
    <div>${html.resolve(
      ongs.then(ongs => ongs.map(ong => html`<li>${ong.name}</li>`))
    )}
 `,
};
```
Pay attension to `html.resolve` method and how your ongs are iterated - a map function should return template.

Your `ongs` property is not related to any other property, so `getOngs()` is called only once, when `render` requires it.

**Comment by DavideCarvalho** [comment]
Thanks for the help
I've changed the code, but I'm getting "template is not a function"
```javascript
const resolveOngsPromise = ongsPromise => html`
  ${html.resolve(
    ongsPromise.then(ongs => ongs.map(ong => html`
      <li>
        <div class="collapsible-header">${ong.name} - ${ong.taskTitle}</div>
        <div class="collapsible-body"><span>Lorem ipsum</span></div>
      </li>
    `)),
  )}
`;

const ongsListRender = ({ ongs }) => html`
  ${materializeStyle}
  <h1>Help My.ONG</h1>
  <ul class="collapsible">
    ${resolveOngsPromise(ongs)}
  </ul>
`;

const ongsList = {
  ongs: getOngs(),
  render: ongsListRender,
};
```

**Comment by DavideCarvalho** [comment]
I tried removing the ```html``` from ```resolveOngsPromise``` and still doesn't work

```javascript
const resolveOngsPromise = ongsPromise => html.resolve(
  ongsPromise.then(ongs => ongs.map(ong => html`
    <li>
      <div class="collapsible-header">${ong.name} - ${ong.taskTitle}</div>
      <div class="collapsible-body"><span>Lorem ipsum</span></div>
    </li>
  `)),
);
```

**Comment by smalluban** [comment]
You can't do this:

```javascript
const ongsList = {
  ongs: getOngs(),
  render: ongsListRender,
};
```
This is the definition of your properties, not values... It should be:

```javascript
const ongsList = {
  ongs: () => getOngs(), // <-- it has to be a function, not a promise value
  render: ongsListRender,
};
```

**Comment by DavideCarvalho** [comment]
Sorry for the silly mistake. But even after changing it I'm getting the same error

```javascript
const resolveOngsPromise = ongsPromise => html`
  ${html.resolve(
    ongsPromise.then(ongs => ongs.map(ong => html`
      <li>
        <div class="collapsible-header">${ong.name} - ${ong.taskTitle}</div>
        <div class="collapsible-body"><span>Lorem ipsum</span></div>
      </li>
    `)),
  )}
`;


const ongsListRender = ({ ongs }) => html`
  ${materializeStyle}
  <h1>Help My.ONG</h1>
  <ul class="collapsible">
    ${resolveOngsPromise(ongs)}
  </ul>
`;


const ongsList = {
  ongs: () => getOngs(),
  render: ongsListRender,
};

// getOngs
export const getOngs = async () => {
  const data = await fetch(`${url}/ongs`);
  const jsonData = await data.json();
  return jsonData;
};
```

**Comment by DavideCarvalho** [comment]
Even after changing getOngs implementation to: 
```javascript
export const getOngs = () => {
  return fetch(`${url}/ongs`)
    .then((res) => res.json());
};
```
The error stays

**Comment by smalluban** [comment]
This was my mistake. The first `.then()` should return template. By the way, you have one additional wrapper over the result. 

```javascript
const resolveOngsPromise = ongsPromise => html.resolve(
  ongsPromise.then(ongs => html`
    ${ongs.map(ong => html`
      <li>
        <div class="collapsible-header">${ong.name} - ${ong.taskTitle}</div>
        <div class="collapsible-body"><span>Lorem ipsum</span></div>
      </li>
    `)}
  `)
);
```

`html.resolve` returns update function, so it does not have to be wrapped with additional `html` call.

**Comment by smalluban** [comment]
It is not required, but it is recommended and the easiest way. If course I mean using promises inside of the html template.

Feel free to comment or re-open, if you have any other problems this subject.

**Comment by DavideCarvalho** [comment]
Could you please demonstrate other ways to do async stuff with Hybrids? I've used with redux and it was really easy, but I'd like to know how to do it in a more vanilla way.
Html.promise is a really cool stuff, but I'd like to know if there is other way without having to encapsulate my html inside html.promise

**Comment by smalluban** [comment]
Try to think about async stuff as something that is a promise in the synchronous world. Then you can do anything async in the library, but return a promise and consume it somehow. They can be simple getter - function which returns promises.

Redux example shows how to connect third-party code to cache mechanism. It doesn't have to be async. Redux is not async. However, the redux store update might be called by the external change and we want to listen to that. In that sense, you should use the third argument in the `connect()` callback to connect your external API - it can be anything - setTimeout, web socket, Geolocation API, whatever.

`html.resolve` is a helper to consume promises and async values in templates. If I would compare to `lit-html` it works pretty the same here and there. The only difference is, that `lit-html` has `until()` directive. If you have any ideas on how to make it simpler, I am here to listen to you :)

**Comment by dredzone** [comment]
is it possible to have an async / promise property factory that normalizes async data? 
for example:
```
define("my-app", {
  data: promisePropertyFactory(defaultValue, serviceApiCall());
})
```

**Comment by smalluban** [comment]
I would suggest passing a promise as a value of the property as I wrote before. Then you can utilize a promise in the template by `html.resolve` helper. However, if you want to have the data from a promise in the property, the only way is to call your async API in the `connect` method:

```javascript
MyApp = {
  data: {
    connect(host, key) {
      host[key] = defaultValue;
      serviceApiCall(...).then(data => { host[key] = data });
    },
  },
}
```

You can always create the factory from property structure, like this:

```javascript
function promiseFactory(promise, defaultValue) {
  return {
    connect(host, key) {
      host[key] = defaultValue;
      promise.then(data => { host[key] = data });
   },
}

const MyApp = {
  data: promiseFactory(callMyApi("/api"), "test"),
};
```
Keep in mind that this solution has a significant downside. Connect method is called whenever the element is connected to the parent element - it means, that moving your element around will re-fetch data (and pass defaultValue). Even though it stays, fetch will be done only once, and *cannot* dynamically relay on other properties.

Because of that, the better way (and more declarative) is to pass your async function inside of the property getter:

```
const MyApp = {
  data: ({ otherProperty }) => callMyApi(`/api/${otherProperty}`),
};
```

The data property will always return a promise - but only a new one when `otherProperty` changes. It might look strange at first (we get used to working on data rather then promises). I understand your concerns, and I actively working on a built-in solution to store async data inside of the hybrids ecosystem. Please stay tuned for updates, and for now, use possible solutions.
