### ISSUE TITLE
Allow storing an object in a component property

### ISSUE THREAD

**Issue by Qsppl** [hybridsjs/hybrids#257]
Due to the fact that it is forbidden to store objects in the property, I have to store the string identifier of the objects and retrieve the corresponding objects through a singleton when they are needed.

Or make default values ​​`undefined` and then assign real values ​​to undefined properties in the component initialization function.

![image](https://github.com/hybridsjs/hybrids/assets/22717464/665731a8-8aa8-42a8-a1ee-fc23e792b3c6)

![image](https://github.com/hybridsjs/hybrids/assets/22717464/828ca41c-d0f9-48a2-9703-1272c4cd9837)

This breaks the types and looks ugly. Is it possible to add the ability to write such code more declaratively?

**Comment by smalluban** [comment]
In v9 it will be possible to set the default value to any type when set by the full object descriptor. It's coming, but still, one missing feature is in "work in progress". I think it should be ready next week.

**Comment by Qsppl** [comment]
Thank you very much, I'll wait.

**Comment by smalluban** [comment]
`v9.0.0` has been released, so it is possible now to set the property as an object instance. Feel free to re-open if you find any issues with that.

**Comment by Qsppl** [comment]
Thanks
