### ISSUE TITLE
Scoped CSS

### ISSUE THREAD

**Issue by fruitbang** [hybridsjs/hybrids#264]
I want to ask is it still possible to use Scoped CSS in hybrids?
I can't use ShadowDom, cuz such libraries as "pdfmake", don't have the ability to go into the shadows, and for that I would like to use this extremely useful feature.

**Comment by smalluban** [comment]
You can do anything, which is valid HTML code in your template. You are not force to use `css` helper method for styling, you can use ordinary `<style>` element, etc..

```js
render: {
  value: () => html`
    <div>...</div>
    <style>....</style>
  `,
  shadow: false,
}
```

However, I am not sure what kinds of scoped CSS you mean. Do you want to use new `@scope` rule? https://developer.mozilla.org/en-US/docs/Web/CSS/@scope

**Comment by smalluban** [comment]
There is built-in layout engine, which works without the Shadow DOM. You can check it out, but it focuses on "layout" CSS rules. 

However, if you are forced to put something in Light DOM, you can still create other parts using Shadow DOM.

Hybrids v9 detects automatically if Shadow DOM is required, and only uses it if it's required (slot element, or styles). Usually, it's not needed.

**Comment by Qsppl** [comment]
What he means is that VueJS implements scoped-css by adding a hash unique to that component to each element in a component, as well as the same hash to each selector declared in the component:
![image](https://github.com/user-attachments/assets/2ceb9496-135f-41de-b96c-af27c494853d)

I was unable to reproduce this behavior on hybrids: [example](https://codepen.io/qsppl/pen/zYVzzjX?editors=1010)

[CSS scope](https://developer.mozilla.org/en-US/docs/Web/CSS/@scope) is not yet supported by browsers.

**Comment by smalluban** [comment]
The layout engine is doing exactly that - it takes CSS properties, creates a unique class, and applies it to the element with `layout="..."` attribute. However, by the design, it only focuses on layout properties, as everything else should be defined in its own UI elements (using classical CSS), or by the additional styles in the main template (where layout is being used). The main goal here is to avoid a lot of structural CSS, which is usually unique to each view (not repeatable, as then it should be included in one UI element).

I am not sure if there is anything else we can help you with the issue. I encourage to use selectively Shadow DOM, where it is possible - as you don't have to do it everywhere - all of the browsers support it.

**Comment by smalluban** [comment]
I explained possible ways to scope CSS using internal tools of the framework. However, @fruitbang feel free to re-open if you need more guidance.
