### ISSUE TITLE
Component properties cannot be setted until they are observed

### ISSUE THREAD

**Issue by Qsppl** [hybridsjs/hybrids#266]
example: https://codepen.io/qsppl/pen/LYKLoJJ

The observed behavior is not obvious. The first time library users encounter this behavior, it will be confusing.

**Comment by smalluban** [comment]
Is this valid? As some of the actions fail with the new version (as setting values in the value function is forbidden)?

**Comment by Qsppl** [comment]
Oh, this is no longer relevant. The issue is resolved in another question: https://github.com/hybridsjs/hybrids/issues/265
