### ISSUE TITLE
store.record(store.record('')) bug

### ISSUE THREAD

**Issue by fruitbang** [hybridsjs/hybrids#269]
I'm trying to figure out how the store.record() works.
So i made small application, which you can see at this link:

https://stackblitz.com/edit/vitejs-vite-kpw862?file=src%2Fmain.ts

Then I had a few questions:

1. The documentation says: "The record is a map of all of the supported types of properties (including nested objects and arrays):", so i expect that values (properties) of Record ​​can be primitive types, as well as arrays and objects, but store.record() function only accepts primitives, and another store.record() function, so this imposes many restrictions, and produce a strange behavior of this feature, like not obvious type casting. Is this information in the documentation valid?
2. So, when you use only one level of store.record('') - the result looks adequate, and everything works as expected.
![image](https://github.com/user-attachments/assets/15caae01-0b15-4e7d-a25e-f6d260282af8)
But, when you use something like this: store.record(store.record('')) - first level starts looking weird, after casting to an iterable type, and when you use external storage, the lists sometimes work, then throw an error.
[Screencast from 2024-09-02 19-44-44.webm](https://github.com/user-attachments/assets/b68c5d61-4d52-4be2-b1f3-fe994505c699)

**Comment by smalluban** [comment]
The `address: store.record('')` works just fine. I think the problem is that you use that feature in the wrong context. The `store.record()` requires **one** type of the value of the keys. In your example, the `address` contains `geolocation`, which is another object. 

Avoid using `store.record()` for known structures. Its main purpose is to allow the creation of models with object-based maps of values rather than arrays with special structures, like `values: store.record('')` rather than `values: [{ key: '', value: '' }]`.

In your example, you should set:

```
address: {
  geolocation: { lat: '', long: '' },
  city: '',
  street: '',
  number: 0,
  zipcode: '',
}
```

**Comment by fruitbang** [comment]
>The store.record({}) works just fine, you need to have a proper model definition in TypeScript. The type allows to pass anything matching the Model constraints - https://github.com/hybridsjs/hybrids/blob/main/types/index.d.ts#L286
>
wow, this really works!
I think i was probably confused by the fact that if I use store.record([]), the following error is displayed:
"Uncaught TypeError: The value of the 'value' must be a string, number or boolean: undefined"
maybe if more examples are added to the documentation, it will not have such effect as my stupid example above.
>address: {
  geolocation: { lat: '', long: '' },
  city: '',
  street: '',
  number: 0,
  zipcode: '',
}
>

BUT THIS IS MUCH MORE IMPRESSIVE!!!
How long ago did this appear?
Previously I needed to create separate models for nested objects, then store.record appeared and I thought that this is the correct way to create models with a nested structure.

Thanks for the detailed answer, but still, maybe it's worth paying attention to this random error: "TypeError: can't convert undefined to object", which is shown in the video in the example above, cuz sometimes it's works just fine, and sometimes not...
