### ISSUE TITLE
@FontFace polyfill for adopted stylesheets in shadow roots

### ISSUE THREAD

**Issue by Qsppl** [hybridsjs/hybrids#277]
Currently, the `@font-face` css rule does not work in the chrome browser when used in component styles.

https://issues.chromium.org/issues/41085401

https://stackoverflow.com/questions/63710162/how-to-load-font-face-in-dynamically-loaded-styles-of-web-component-with-shadow

Is it possible to add a polyfill to `html``.styles()` & `html``.css()` that will solve this problem?

**Comment by smalluban** [comment]
How would you like to polyfill the feature? If you mean adding those `@font-face` rules into the main document, it won't be a polyfill anymore. After all, it is just the same as you would define your fonts globally.

The case here is to create those rules scoped only to the current shadow root. This might be technically not possible (like a full polyfill of shadow DOM itself). This problem can't be addressed at the library level.

**Comment by Qsppl** [comment]
Adding @font-face rules to the main document is, for now, the only possible compromise.

Adding @font-face to the main document is dangerous, since there is a possibility of overriding some font family, so you can make this feature optional.

Otherwise, we need to at least add a warning about this problem in the chromium browser to the documentation so that library users do not waste time searching for the problem.

**Comment by smalluban** [comment]
There are a few facts against the feature:
1. Polyfills from their nature are global monkey-patch style libraries - they should work with all things, not only in one library
2. The only way to pass `@font-face` rules in Chrome would be to put them at document level - which is not a polyfill and can break things - as it won't work like in Firefox or Safari (if that support that)
3. We always have to deal with situations where one browser or another has not yet implemented things - it's unfortunate that this time the feature cannot be polyfilled correctly - if it could be - I suppose there was an npm package for that already
4. Even if we try to implement it, I would have a dozen other technical questions about how we can do that - for example, how can we detect that this is not supported?

Considering the above facts, I am against implementing this in hybrids. After all, what you would like to do at the library, you can easily do by yourself. If your application needs those fonts to work in Chrome, they must be set on the document level.

**Comment by Qsppl** [comment]
Yes, changing the headers of the main document in order to include fonts in the component is really inappropriate.

I thought about it and now I understand that I should rather add notes on this topic [to the MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_shadow_DOM).

Thank you for clarifying this issue.
