### ISSUE TITLE
How to actually implement enumerable local storage store model?

### ISSUE THREAD

**Issue by techninja** [hybridsjs/hybrids#279]
Hey, loved the project for years, you guys are great! Working on implementing hybrids and state management for the [new frontend](https://github.com/techninja/ninjanode/tree/pixi-renderer) for [my old space ship game](https://ninjanodebeta.tn42.com/). Everything has been a breeze to implement and I love the complete lack of build system utilizing modules and import maps native in the browser!

Though this is my third hybrids project, this is my first attempting to utilize the `store`. I feel like there's something I'm definitely missing in my understanding. The good news is this entire implementation is clientside, the main thing I want is to store an enumerable state entirely within local storage. The in-memory store works wonders for my feature as it stands, but as soon as I [try my hand at writing a `store.connect`](https://github.com/techninja/ninjanode/blob/pixi-renderer/public/data/stateModels/BotConfig.mjs#L13-L42), state never updates except after writing and fully reloading.

For brevity here's my attempt at the state connect key inside my state model linked above:

```javascript
[store.connect]: {
  list: () => {
    const vals = Object.values(
      JSON.parse(localStorage.getItem(storageKey) || '{}')
    );
    return vals;
  },
  get: (id) => {
    const data = JSON.parse(localStorage.getItem(storageKey) || '{}');
    return data[id];
  },
  set: (id, values) => {
    const data = JSON.parse(localStorage.getItem(storageKey) || '{}');
    // Null means delete the entry.
    if (!values) {
      delete data[id];
    } else if (data[values.id]) {
      // Existing entry, fold in new values.
      data[values.id] = { ...data[values.id], ...values };
    } else {
      // Set new value entry.
      data[values.id] = values;
    }
    localStorage.setItem(storageKey, JSON.stringify(data));
    return values;
  },
},
```

This saves the ID keyed object to a JSON string where the name is a string in `storageKey`, but when fetching the state right after setting it, even though I can clearly see the data saved correctly to local storage,  hybrids components don't get a triggered re-render, and reading the `store.get([BotConfig]).length` reads `0`.

My far simpler [non-enumerable store model for `UserSettings`](https://ninjanodebeta.tn42.com/) worked great from the start, and without attempting to CRUD to local storage the in-memory default state storage works perfectly from that branch so I'm not sure what's up. 🤔 

Also here's the [PR with screenshots](https://github.com/techninja/ninjanode/pull/77) of the UI the enumerable state powers, works so well in-memory as is!

**Comment by smalluban** [comment]
The `list()` method in the store model definition takes arguments. If the source is external (there are get, set or list methods in the definition), the store cannot "reset" the listing after updating or adding an item, as it might not be true. For example, you can have a list of items with arguments pointing to a subset of the list. Adding a new item should not clear that already fetched list.

That logic would be more obvious if the source of data is the API end-point. However, if you define `[store.connect]` store assumes that this is external.

For this reason, there is a `loose` option, which does exactly what you would like to have. Please read this section of the documentation: https://hybrids.js.org/#/store/storage?id=loose

For your case, you should set it to `true`.

Another thing - you can optimize access to the localStorage - create a global variable for "memory" access, and only update the whole object when is a change (like flushing changes):

```js
function connectLocalStorage(key) {
  const models = JSON.parse(localStorage.getItem(key) || '{}');
  return {
    get: (id) => models[id],
    set: (id, values) => {
      if (values === null) {
        delete models[id];
      } else {
        models[id] = values;
      }
      
      localStorage.setItem(key, JSON.stringify(data));
      
      return values;
    },
    list: () => models,
    loose: true,
  };
}

const MyModel = {
  value: 'test',
  [store.connect]: connectLocalStorage('MyModel'),
};
```

**Comment by techninja** [comment]
Thanks so much for the fast reply! I think for `models` you meant `data`? Also if we're keying on the object, we need to return an iterable on `list`, not the object.

Also with an enumerable state, it seems the ID argument is initially `undefined`, but the ID is clearly in the values?

<img width="285" alt="Screenshot 2024-12-31 at 10 07 13 AM" src="https://github.com/user-attachments/assets/e0ee9258-7be8-4686-ab62-a852b7f15aad" />

This is what I ended up with, and it works wonderfully.
```javascript
const connectLocalStorage = (key) => {
  const data = JSON.parse(localStorage.getItem(key) || '{}');
  return {
    get: (id) => data[id],
    set: (id, values) => {
      if (values === null) {
        delete data[id];
      } else {
        data[values.id] = values;
      }

      localStorage.setItem(key, JSON.stringify(data));

      return values;
    },
    list: () => Object.values(data),
    loose: true,
  };
};
```

Should we actually expect that ID argument in `set: (id, values)` to be `undefined` for initial set?

**Comment by smalluban** [comment]
Yeah, you are right. I was writing code ad hoc :) 

The id is undefined when you create a model, but the model values have an id set to UUID, so you can either use it or return your own id.

**Comment by techninja** [comment]
Great! Hopefully this thread helps someone, certainly helped me! Thanks again, and have a happy new year! 🥳
