### ISSUE TITLE
Benchmark

### ISSUE THREAD

**Issue by vogloblinsky** [hybridsjs/hybrids#29]
Hi,

Here is the link to the results for a simple TodoMVC app : https://vogloblinsky.github.io/web-components-benchmark/

Source code here : https://github.com/vogloblinsky/web-components-benchmark/tree/master/todomvc/hybrids

**Comment by smalluban** [comment]
I don't know If I suppose to see hybrids results in the first link because they are not there :) About the source code, it looks pretty good, in the terms of performance I have no comments. 
For dispatching events hybrids provides `dispatch` helper - you then don't have to create CustomEvent explicit, but it has no impact on the perf.

**Comment by vogloblinsky** [comment]
Sorry, the last build breaks druign the night and revert to a previous version of the page where Hybrids was not listed. Have a look now.
I will updated the code for using your dispatch helper ;)

**Comment by smalluban** [comment]
Cool. I looked at the results. I think they are promising, as I have never test performance before. It was my concern during the implementation, but not tested :) 

Thanks for your work!

What I have to do, is to inspect your pascal triangle test. Hybrids seems to be slow on that. 

One question, did you consider to add live links to the implementation? For example, if I click on hybrids, it would open new tab with working todo app :)

**Comment by vogloblinsky** [comment]
Benchmark updated with demos : https://vogloblinsky.github.io/web-components-benchmark/

**Comment by smalluban** [comment]
Few issues found:
* Demos backlink does not work
* It opens in new tab (maybe it is intentional)

Other case is with results. They have changed. Do you use some weighted average or other thing and call tests multiple times to avoid measurement errors?

**Comment by vogloblinsky** [comment]
There is another release coming in Travis for backlink issue.

For results, i will explain in details in a future blog post. I call each test 10 times, and do an average.

For the machine, it is running on Travis CI, may be you can find informatiosn here in the log : https://travis-ci.org/vogloblinsky/web-components-benchmark/builds/469567920

**Comment by smalluban** [comment]
I am not sure if Travis CI for open source projects can provide consistent performance. Even though the relative differences between results might be similar, the absolute values can differ.

There is https://github.com/krausest/js-framework-benchmark project, which uses the best result as a reference to the rest. I could help with your case.

**Comment by vogloblinsky** [comment]
Yes, i know this other great benchmark project, which run on Travis too :)

**Comment by smalluban** [comment]
I looked at hybrids core for the triangle test and one obvious improvement can be use a key index. Generated template has a helper method for setting custom key id for efficient reorder of list items. 

You can find more here https://hybrids.js.org/template-engine/iteration#keys

**Comment by vogloblinsky** [comment]
Ok, implemented, CI is running, will see if it is better in 1h.
