### ISSUE TITLE
render: "<slot>" doesn't work if not in shadowRoot mode

### ISSUE THREAD

**Issue by davidgraeff** [hybridsjs/hybrids#33]
That should be listed as a limitation somewhere.

**Comment by Danny-Engelman** [comment]
It is the distinction between Light DOM and Shadow DOM in Custom Elements
When a Custom Element has a Shadow DOM it is called a Web Component

You can refer to:
https://developers.google.com/web/fundamentals/web-components/shadowdom#composition_slot
