### ISSUE TITLE
Support for built-in elements

### ISSUE THREAD

**Issue by LucaMele** [hybridsjs/hybrids#36]
Hello,

I might be wrong but in the documentation i couldn't find any voice about built-in elements and wanted to know if there is support or if not when is planned to come?

REF: https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-customized-builtin-example

**Comment by smalluban** [comment]
You can find answers for your questions here: #34. As this is a second try to this subject, I will add an item to my todo list with updates of the docs. It might be a good idea to explain it somewhere in the docs.
