### ISSUE TITLE
PostCSS support?

### ISSUE THREAD

**Issue by dangodev** [hybridsjs/hybrids#37]
It’d be great to have a hook, or ability to run a preprocessor in the `<style>` template. This would basically allow nested declarations, CSS variables, and other polyfills/plugins PostCSS affords. 

Because PostCSS spits out standards-compliant CSS, it could just spit out the plain-CSS result back to `<style>` and let Hybrids do its thing normally. So long as it happened as the first step.

Would it be possible to allow for a transform function to happen before shadycss reads the `<style>` template?

**Comment by smalluban** [comment]
If you are using PostCSS in your toolbelt, I suppose that you are also using bundler, like webpack, rollup or parcel.  With `v2.0.0` release, library supports passing style content to ``html`...`.style()`` helper. You can find more about it in [this section](https://hybrids.js.org/template-engine/styling#css-stylesheet) of the docs. With this option, you can easily set up your project to import text content of CSS file:

```javascript
// `styles` should contain text content of CSS file
import styles from './MyElement.css';

const MyElement = {
  render: () => html`
    <div>...</div>
  `.style(styles),
};
```
It is the best way to support CSS pre-processors. The template engine uses `<template>` element to parse text into real nodes. In IE11 passing not correct CSS into the `<style>` element removes that content, so it is not possible to create `<style>` element and then replace it with transpiled version.

**Comment by dangodev** [comment]
That makes sense. I’m all for simplifying the workflow and letting each piece do its own thing.

Is there a recommended setup for webpack in the docs? Or if not, would that be a helpful page in the docs I could help contribute to?

**Comment by smalluban** [comment]
I'm not sure if docs are the right place for webpack config documentation. There always be something missing or outdated. What we can do is to add links to webpack docs, or loaders, that allows importing CSS files with their content, instead of creating global styles in the document head. If so, you can change links or add a sentence to the section, which I already linked - https://hybrids.js.org/template-engine/styling#css-stylesheet.

I didn't test that kind of setup by myself, so let me know if you could do it with webpack, and it works with `style()` helper method :)

**Comment by dangodev** [comment]
I was able to get it working with webpack 🎉! This was my setup:

**instal**
```
npm i --save-dev raw-loader postcss-loader postcss postcss-preset-env
```

**webpack config**
```js
const postcssPresetEnv = require("postcss-preset-env");

module.exports = {
  module: {
    rules: [
      {
        test: /\.css$/i,
        use: [
          "raw-loader",
          {
            loader: "postcss-loader",
            options: {
              plugins: () => [postcssPresetEnv({ "nesting-rules": true })] // example of plugin w/ options
            }
          }
        ]
      },
}
``` 

What’s very important is that you use `raw-loader` and **only** raw-loader. If you add `css-loader` or `style-loader`, then webpack will start treating it like a CSS file. raw-loader, by comparison, just tells webpack “it’s just a string don’t worry about it,” then it passes it off to the `style()` function for Hybrids to worry about.

**Comment by smalluban** [comment]
Ok, so my assumptions were wrong, and we could write a sentence about webpack better in the docs. If you want to contribute, you are very welcome :) I think we can even place there a separate paragraph after the code example instead of notice in the brackets.

**Comment by dangodev** [comment]
Cool. Threw [this](https://github.com/hybridsjs/hybrids/pull/38) together real quick. Feel free to modify/change anything!
