### ISSUE TITLE
is this library done?

### ISSUE THREAD

**Issue by bboydflo** [hybridsjs/hybrids#39]
maybe not the right place to ask but here I go. Is this library done? are there any plans for new features? I'm asking because I've read the docs and everything seems super easy to understand and feature complete. that's why I'm wondering

**Comment by smalluban** [comment]
Core features are done. I am focused now on making docs better and spread the news about the library to the community. However, I am open to any suggestions. As you can see in the changelog, new versions are released quite often. There is opened an issue for creating typings, etc.

I suppose that more complex features can be delivered as separate packages with reusable factories. Although, if you have an idea how to make it simpler and better, feel free to present your concepts :)

I'm happy that docs seem to be easy to understand :)
