### ISSUE TITLE
appreciate your feedback for custom element reactions diagram

### ISSUE THREAD

**Issue by AndyOGo** [hybridsjs/hybrids#41]
I just released an adapted version of the interactive react lifecycle methods diagram for custom element reactions:
https://andyogo.github.io/custom-element-reactions-diagram/

If you have time, I would appreciate your feedback very much.

**Comment by smalluban** [comment]
Overall it is done quite well. I am not sure of the purpose, but I have some highlights:

* define is not one of the element reactions, a complete list is described in the specs [here](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-reactions), so I think this "Unknown phase" is not needed here.
* connectedCallback/disconnectedCallback is also called when an element is moved from one place to another. I know, that in that process an element is disconnected, but your diagram and explanation suggests, that it works more like React components, which only calls unmount when the component is going to be destroyed.

**Comment by AndyOGo** [comment]
@smalluban 
Thanks for your great feedback.

I agree with you, strictly speaking only `constructor`, `define`, aren't part of what are custom element's reactions.
Maybe **lifecycle** is a better fit, though I wanted to avoid that people start to think with React paradigms in mind and therefore use other terms by intention.

Indeed, there are many initiators for `connectCallback` and `disconnectedCallback`, i.e. the whole DOM API - but I wanted to avoid to include the whole API.
Maybe it helps to prefix the initiators by **e.g.** to clarify that this is only one possibility?

The purpose is to increase awareness and understanding of custom elements, to help people find relevant parts in the spec and actually study them carefully.

**Comment by AndyOGo** [comment]
@smalluban 
Done, Thanks a lot.
I have added now at least two examples of the DOM API being marked as [`[CEReactions]`](https://html.spec.whatwg.org/multipage/custom-elements.html#cereactions) extended IDL attribute.
