### ISSUE TITLE
Dependencies page feedback

### ISSUE THREAD

**Issue by lucaseverett** [hybridsjs/hybrids#42]
When using the .define helper method, it seems as if it automatically translates from UiHeader to ui-header when creating the definition, but it isn't explicitly documented that it does the translation for you based on the use of camel case.

At least in my case, I was confused upon reading the documentation, but I figured it out when using the method. It might be helpful to document that functionality, though.

**Comment by smalluban** [comment]
Helper `define` method for `html` is nothing more than a `define()` function from the library. You can find explanation in the dependency page:

> It uses define function from the library, so its API is similar to described in the Definition section.

And there is a link to definition section. I think it is sufficient, but if you think that it could be documented better feel free to open PR.

**Comment by lucaseverett** [comment]
Thanks for the response. Yes, I read the documentation for define, but I didn't see anything explaining that there was an automatic conversion from camel case to hyphen.

After spending some time reading the documentation and not being able to understand how it was working, I decided to just try it out, and that's when I understood what was happening.

I just wanted to share my feedback in case anyone else got stuck trying to understand how the name resolution worked.

**Comment by smalluban** [comment]
I will put it in my docs to do list, and write more explicit sentence about it. However, in define docs section, there is a description for passing a map, and it is explained that keys are translated to dashcase. 

Thanks for the feedback :)
