### ISSUE TITLE
Property map argument for custom element constructors

### ISSUE THREAD

**Issue by knoan** [hybridsjs/hybrids#44]
Would it be possible to extend the custom element constructor returned by [`define()`](https://hybrids.js.org/misc/api-reference) as to accept an optional property map with custom values for the component properties?

Suppose I defined an Icon component like:

```javascript
export default define('custom-icon', {

    name: "",

    render: ({ name }) => { … }

});
```

It would be very convenient if I could initialise required properties when creating from javascript like:

```javascript
import Icon from "…/Icon"

new Icon({
    name: 'alert'
})

```

Instead of:

```javascript
import Icon from "…/Icon"

const icon=new Icon();

icon.name='alert';
```

P.S. kudos for the outstanding work :-)

P.P.S besides gitter, do we have a conventional forum for discussing lengthier doubts/proposals? If not, is it acceptable to create question issues here?

**Comment by smalluban** [comment]
Custom elements API saves class constructor generated by the library, so extending returned constructor won't work. Passing custom parameters to the constructor is only possible when you create a class by hand. 

However, If you want to initialize your custom elements in JS you can create a helper function for that:

```javascript
import Icon from '../Icon';

export function createIcon(name, size) {
  return Object.assign(new Icon(), { name, size });
}
```

The preferred way to consume custom elements is HTML template (in document, fragment or content of other custom elements):

```
<custom-icon name="alert"></custom-icon>
```
The above way is declarative and does not require using JS at all to initialize element.

P.S. -> Thanks!
P.P.S -> For now, you are welcome to create an issue for any subject related to the project. There is no official forum other than gitter chat.

**Comment by knoan** [comment]
Thanks, `Object.assign` would do for now.

```html
<custom-icon name="alert"></custom-icon>
```

> The above way is declarative and does not require using JS at all to initialize element.

Agreed, but sometimes you are required to provide programmatic access to widgets in a component library…
