### ISSUE TITLE
Using/Mix in W3C standard custom element - error: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.

### ISSUE THREAD

**Issue by Danny-Engelman** [hybridsjs/hybrids#49]
Is this a StackBlitz or Hybrids limitation?

![image](https://user-images.githubusercontent.com/3382713/56268070-d8f71600-60f0-11e9-9788-1e48624f6d36.png)

**Comment by smalluban** [comment]
Custom Elements API requires real `class` - here StackBlitz transpiles your code to ES5. Hybrids library internaly uses a simple hack to construct class definition, that works with API. Components defined with hybrids will work.

However, you are using a plane class definition. To make it work with ES5, you need a polyfill for that case. Fortunately, there is already prepared 
 - https://github.com/webcomponents/webcomponentsjs#custom-elements-es5-adapterjs
