### ISSUE TITLE
Try to set key in get call error

### ISSUE THREAD

**Issue by dredzone** [hybridsjs/hybrids#52]
emitting custom event from inner element element and attempting to set outer element property causes "Try to set key in get call" error

**Comment by smalluban** [comment]
Can you provide a failing example? It can be on some online editor. It looks, that you dispatch event inside of the getter, which then observed (synchronously) by another element try to set its own property. 

Cache mechanism wraps `get` and `set` methods, and saves dependent `get` calls invoked inside. To prevent an endless loop of setting and getting and to protect the correct dependency tree, it is forbidden to set properties inside of the getter.

One solution can be triggering event asynchronously, like this:

```
Promise.resolve().then(() => dispatch(host, 'your-event-type', ...));
```

However, I would advise to not create side effects inside of the getter and use today introduced `observe` method.

**Comment by dredzone** [comment]
moving dispatch event into observe does the trick, thank you.
