### ISSUE TITLE
A helper to render defined element into body on runtime

### ISSUE THREAD

**Issue by threeid** [hybridsjs/hybrids#59]
Hello  Dominik Lubański,

I'm learning Hybrids.js and it is cool. 
Come from React, Vue, they just need an `index.js` and include it in `index.html`,
which is great way to get start!

And sometime, i want to have an element render at runtime and append it to body or `app` div.
It would be great if just import an utility function from hybrids and it works:
```javascript
renderTo(
  document.body, // or document.querySelector('#id')
  `<simple-counter count="10"></simple-counter>`
)
```

Thanks for reading.
NPTien

**Comment by smalluban** [comment]
Custom elements are part of the web platform. You don't need external tools for creating them. If you define your `<simple-counter>` with `define()` from the library (and include the script in your document), you can create it like any other element:

```javascript
const el = document.createElement('simple-counter');
document.body.appendChild(el);
```
