### ISSUE TITLE
Make Hybrids.js more beginner-friendly

### ISSUE THREAD

**Issue by threeid** [hybridsjs/hybrids#60]
Hi Dominik Lubański 

React, Vue are very beginner-friendly.
Especially for someone like me who want to see the results fast by
clone a repo, type `yarn && yarn dev` and hit enter,
edit code and see changes immediately in browser.

That is a great selling point. I want to clone a repo and start from there
instead of configing webpack or parcel.

Have a `create-hybrids-app` with some templates is great!
 
Another thing that i want to request is that include all the live examples in `/example` this repo or another repo `examples` in hybridsjs org.
Looking at VSCode is better than looking at browser in working time. ;D

Thanks for reading.

NPTien

**Comment by smalluban** [comment]
Hybrids is a library for creating web components. It is not a framework for building apps. I know that it would be great to have an easy way to build apps using the library, but it requires some work, which is yet ahead (especially view management, like routing). The structure of building the whole framework should be as follows:

1. The platform (custom elements, Shadow DOM, etc)
2. Library for building web components using the platform
3. State management (currently in progress) - store for async data
4. Skeleton for routing and view management

If we combine all of that, then will be possible to create a project, which allows building apps with hybrids.

However, you are welcome to build some boilerplate repository with pre-configured tools for building simple apps. You should find web components for routing and create state management (you can use redux or something else).

The library can be used directly in the browser (even in IE11), so it is super easy to start - only what you have to do is to include one script tag. Also, you can use demos from the documentation and play with the library online. There is also a nice project with a playground for web components libraries - https://webcomponents.dev/ - you can find hybrids there as well.
