### ISSUE TITLE
Is attribute not work in html function

### ISSUE THREAD

**Issue by krvpb024** [hybridsjs/hybrids#68]
Hi

I'm trying to use `is` attribute to specify custom element. It works fine when I use it directly in html file, but I can't get it  works in html function. It works normally when I use the tag name directly.

Here's the code.

```js
const indexView = {
  render: render(function renderIndexView (host) {
    return html`
     <!-- it not works -->
      <form is="form-el"></form>
     <!-- it works -->
      <form-el></form-el>
    `
  },
  { shadowRoot: false })
}
```

Is there something I'm doing wrong?

**Comment by smalluban** [comment]
> It works fine when I use it directly in html file

This strugles me, as it means that you defined a [customized built-in element](https://developer.mozilla.org/docs/Web/Web_Components/Using_custom_elements#Customized_built-in_elements), but it does not work inside of the hybrids template. Writing `<form is="form-el"></form>` in the html template without expressions just puts that element in the DOM - it should work properly.

However, I have to mention, that customized built-in elements are not supported by the hybrids library. You can read more about it in the [Introduction section](https://hybrids.js.org/core-concepts/introduction#customized-built-in-elements) of the documentation. 

Are you sure that your `form-el` is not defined by the hybrids? If it's not, can you provide a failing demo at stackblitz.com or https://codesandbox.io?

**Comment by krvpb024** [comment]
I'm sorry I didn't notice this feature is not supported. The element is defined by hybrids. But I found somehow it works in Firefox in some cases.

```html
<!-- index.html -->
<!DOCTYPE html>
<html>
  <head>
    <title>Parcel Sandbox</title>

    <meta charset="UTF-8" />
  </head>

  <body>
   <!-- this will render in firefox -->
    <main is="index-view"></main>
   <!-- this too -->
    <form is="form-el"></form>

    <script src="src/index.js"></script>
  </body>
</html>
```
```js
// src/index.js
import { html, define, render } from "hybrids";

const formEl = {
  render: render(
    function renderFormEl(host) {
      return html`
        <div>
          <label for="text">value:</label>
          <input type="text" id="text" />
        </div>

        <button type="submit">submit</button>
      `;
    },
    { shadowRoot: false }
  )
};

define("form-el", formEl);

const indexView = {
  render: render(
    function renderIndexView(host) {
      return html`
        <h1>Index</h1>
        <!-- it works -->
        <form-el></form-el>
        <!-- not works -->
        <form is="form-el"></form>
      `;
    },
    { shadowRoot: false }
  )
};

define("index-view", indexView);

```
![firefox screen shot](https://user-images.githubusercontent.com/20417513/67003962-c8f8d700-f111-11e9-8565-225cf7417a4a.png)

https://codesandbox.io/s/bold-frost-cqzpw

**Comment by smalluban** [comment]
> The element is defined by hybrids. But I found somehow it works in Firefox in some cases.

😱

I checked it out and you are right. I didn't test it closely, but it looks that elements with `is` which are defined in HTML file and not created dynamically tries to upgrade to custom element even though the custom element is not defined as a customized built-in element. It is definitely a bug, because then `<form is="form-el">` has the wrong prototype (from HTMLElement) so it misses all form functionality like `submit()` method and will not work as it should.

<img width="1021" alt="Zrzut ekranu 2019-10-17 o 15 26 47" src="https://user-images.githubusercontent.com/1906677/67012943-8f64a380-f0f2-11e9-96d2-ec2a5be94717.png">
