### ISSUE TITLE
Selective updates from Redux store

### ISSUE THREAD

**Issue by darrickyee** [hybridsjs/hybrids#82]
I have a Redux store where some properties will be updated frequently and others will update much less frequently.  I was hoping to use the hybrids cache mechanism to limit the number of re-renders on components whose data isn't going to update much.  Is there a recommended way to do this?

Right now I'm using a data-only hybrids component as a parent to the others.  Here is an example: https://stackblitz.com/edit/js-4retwh?file=index.js

The "counter" data updates every second and the "info" doesn't update at all.  If you open the console, you can see that both the "my-counter" and "my-info" components are being re-rendered whenever "my-counter" has its data changed.  I guess it's because both components ultimately depend on the Redux state itself, which invalidates with each update?

In line 35 I have an alternate "MyStore" definition that sets the properties after the Redux state invalidates.  That does what I want, but I was wondering if this is the best way to do it, or if there's some simpler or more elegant way?

**Comment by smalluban** [comment]
The redux store has only global `store.subscribe()` method, so any change to that store causes state to be updated in your `MyStore` element. You can avoid extra updates by connecting the state directly to elements, which use that data. You don't need `MyStore` wrapper.

You can create following factory:

```javascript
const STORE = createStore(combineReducers({ counter, info }));

function connect(mapState) {
  const get = () => mapState(STORE.getState());

  return {
    get,
    connect(host, key, invalidate) {
      return STORE.subscribe(() => {
        // we can add here additional check if cached value equals to the current one 
        // and call invalidate only if it doesn't
        if (host[key] !== get()) invalidate();
      })
    }
  }
}
```

Then use it where you need some data from the store:

```javascript
const MyElement = {
  value: connect((state) => state.someValue),
  ...
};
```

Even though we check the result of the `mapState()`, invalidate might be called more times if the function returns object data not taken directly from the store (eg. each time new object with some data from the store).

You can test fully working code here - https://stackblitz.com/edit/js-ywotyr?file=index.js, I edited your example :) Dev tools console only shows log from the counter.

**Comment by darrickyee** [comment]
Cool, thanks.  To be honest, I'm not 100% set on using Redux, which is one reason I was looking to use a parent component to store data.  The line `if (host[key] !== get()) invalidate();`, is this essentially what happens when you set a new value using `host.myProperty = someNewValue` (or return a value from the set() of a property descriptor)?  In other words, is there anything problematic with my alternate, commented-out example above?

**Comment by smalluban** [comment]
> The line if (host[key] !== get()) invalidate();, is this essentially what happens when you set a new value using host.myProperty = someNewValue (or return a value from the set() of a property descriptor)?

Basically yes, it is similar, the cache checks if a new value differs from the last one, and only if they are not equal state is bumped and observe methods of dependants are triggered (it's here in the code https://github.com/hybridsjs/hybrids/blob/master/src/cache.js#L109)

> In other words, is there anything problematic with my alternate, commented-out example above?

No, it will work. The only difference is that you use that wrapper element, and your state property in `connect()` references your properties directly, so it is not a general solution, that you can re-use everywhere.

In that case, where you use parent -> children pattern you can avoid redux at all, so the only truth would be in the MyStore element. Both options are valid, it's up to you what fits your needs.

**Comment by darrickyee** [comment]
Ok, sounds good.  Here is a simplified version of my current implementation, which is more general:

```
import { property } from 'hybrids';
import { STORE } from './my-redux-stuff';

// Properties with default values
const DEFAULTS = {
    counter: 0,
    info: property({ name: '', age: 0 })
};

// Store/state connector - pass watched properties
const connectReduxState = (store, propList) => ({
    get: store.getState,
    connect: (host, key, invalidate) =>
        store.subscribe(() => {
            invalidate();
            propList.forEach(prop => {
                host[prop] = host[key][prop];
            });
        })
});

export default {
    state: connectReduxState(STORE, Object.keys(DEFAULTS)),
    ...DEFAULTS
};
```

This works just for top-level `state` properties, but I also wrote a utility function that can make it work with nested properties.  I think I like the fact that none of the properties except `state` has to "know" about the store, which I can replace later if needed.
