### ISSUE TITLE
Typescript typing errors

### ISSUE THREAD

**Issue by darrickyee** [hybridsjs/hybrids#89]
Thanks for putting together the TS definitions!  I am not a TS expert my any means, but I ran into a couple issues that I think can be easily addressed:

1. In the `Descriptor` interface: An error is raised if the `connect` method doesn't return a function, even though the return value is optional according to the [docs](https://hybrids.js.org/core-concepts/descriptors#connect).  Changing the return from `Function` to `Function | void` fixed it for me.

2. The `dispatch` function specifies the `host` parameter as `HTMLElement`, meaning an error is raised if e.g. you try to dispatch on `document`.  I changed the type to [EventTarget](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget) since I think that's the usual interface that implements `dispatchEvent()`, but maybe it could be a combination of types.

This is with 4.1.1, fyi.

**Comment by smalluban** [comment]
I will look into it. Thanks for notifying me. At least I now know that there is someone who uses those types ;)

**Comment by smalluban** [comment]
Fixed with fb76ece2d87828a8df96383f43c6819b4927e38e.
