### ISSUE TITLE
disable shadow dom

### ISSUE THREAD

**Issue by lsimone** [hybridsjs/hybrids#91]
I'd really like to use this library but I think I have a blocking issue: for integration reasons, I **cannot use shadow DOM**.

I can use other webcomponent libraries without using it (i.e: lit-element allows the developer to exclude it https://lit-element.polymer-project.org/guide/templates#renderroot ), but I didn't find anything in the _hybrids_ documentation that could help me on this.

Is it feasible? Any hint?

**Comment by smalluban** [comment]
Yes, you can opt-out from the Shadow DOM quite easily. The render factory can take options as the second argument. The only drawback is that you can't use the translation feature, so it must be set directly.

The full explanation can be found here in the docs: https://hybrids.js.org/built-in-factories/render#shadow-dom

**Comment by lsimone** [comment]
I just saw it, thanks, I tried to find it in the wrong place (I thought rather it was a `define()` option).
I'll give a try.

Thank you very much!

**Comment by modmoto** [comment]
The link is dead and I dont find the shadow dom option in the current documentation, is this still possible or was that feature removed?

**Comment by gourmetseasoningsake** [comment]
@modmoto i think you have to use `content` as property key to achieve that.

**Comment by smalluban** [comment]
@gourmetseasoningsake is right, from v7 it is simplified, and you must switch from `render` to `content` property, and it will work as you expect. 

Here you have a working link to the docs: https://hybrids.js.org/#/component-model/structure?id=render-amp-content

**Comment by modmoto** [comment]
perfect, thanks a lot for the quick response =D
