### ISSUE TITLE
Cache throws an exception when an entry doesn't have `contexts`

### ISSUE THREAD

**Issue by sethlivingston** [hybridsjs/hybrids#94]
In this recent commit,

https://github.com/hybridsjs/hybrids/commit/39baaa8fb66ca769e0d50e2928595e59eacf8050#diff-93327db2f0a6f8df9f3d6f9959bbcc80R74

The guard for `depEntry.context` was removed, but it will be undefined for a new entry. Let me know if you need additional information.

**Comment by smalluban** [comment]
I tried to create a use case where it would break, but I couldn't, so I removed the guard, as it showed up on the coverage report. 

If cache entry has deps, it means, that they had to be called inside, so they already register (line 59-61). In that situation, `entry.contexts` must be defined...

If you can reproduce the error, I am happy to add the gourd here and in line 96.

**Comment by smalluban** [comment]
I'm closing the issue, as nothing is happing here. @sethlivingston Feel free to reopen if you find a use case with an error.

**Comment by smalluban** [comment]
@sethlivingston I found a use case where the guard is required. More info in #96.
