### ISSUE TITLE
Templating: Mixed Class Attribute Values Involving Objects

### ISSUE THREAD

**Issue by auzmartist** [hybridsjs/hybrids#95]
Hello @smalluban!
I have a templating use case where I would like to apply a base class and then various additional classes conditionally via an object. Something like this:

```javascript
render: ({disabled}) => html`<button class="btn ${{disabled}}">Click Me</button>`
```
However, I see in the docs that this is not quite possible:
https://hybrids.js.org/template-engine/properties-and-attributes#mixed-values

Because of the string concatenation behavior for mixed values, the above sample produces this:
```html
<button class="btn [object Object]">Click Me</button>
```
Here's a reproduction with the **&lt;simple-counter&gt;** element:
https://stackblitz.com/edit/hybrids-simple-counter-6zhfes

What are your thoughts on adding behavior to apply the [documented class behavior](https://hybrids.js.org/template-engine/properties-and-attributes#class) to mixed values for classes?

---

By the way, I have a workaround. It's not awful, but it's a whole lot more verbose.
```javascript
render: ({disabled}) => html`<button class="btn ${disabled ? 'disabled' : ''}">Click Me</button>`
```

**Comment by smalluban** [comment]
Hi @auzmartist! Indeed, a mixed approach is not supported. In that case, your expression will be used as a string value. However, you can use object value for the class attribute with const names. For example, you can write your workaround using object syntax:

```javascript
render: ({disabled}) => html`<button class="${{ btn: true,  disabled }}">Click Me</button>`
```
Class names from an object are transformed into a set of class names. Then they toggle only if previously they had different states. It touches DOM updates only if needed. You can find source code here: https://github.com/hybridsjs/hybrids/blob/d6eecaa807859b1c41b58d3e4a803c565ff2f8b6/src/template/resolvers/class.js#L1

It is efficient for dinamically created objects in a render function. And if you need even more performance, you can always go back to the mixed approach with setting string value of the class attribute 😜

**Comment by smalluban** [comment]
@auzmartist Feel free to reopen if you need more help with the subject.
